### ISSUE TITLE
AggregateTransformer calls apply/declareOutputs multiple times in pub serve

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1308]
Repro here https://github.com/jakemac53/aggregate_transform_repro, run `pub serve` from within the `test_package` directory. You will see the following output:

```
Loading source assets... 
Loading aggregate_transform_repro transformers... 
classifying test_package|lib/test.dart
Declaring outputs for ids: 
[test_package|lib/test.dart]
Applying transform to ids: 
[test_package|lib/test.dart]
Serving test_package web  on http://localhost:8080
Serving test_package test on http://localhost:8081
classifying test_package|web/test.dart
classifying test_package|test/test.dart
Declaring outputs for ids: 
[test_package|lib/test.dart, test_package|web/test.dart, test_package|test/test.dart]
Applying transform to ids: 
[test_package|lib/test.dart, test_package|web/test.dart, test_package|test/test.dart]
Build completed successfully
```

As you can see `declareOutputs` and `apply` each get called once with only the files in lib, and then again with all files.

If you serve web (or test) directly you get slightly different behavior. Here is a run from `web`.

```
Loading source assets... 
Loading aggregate_transform_repro transformers... 
classifying test_package|lib/test.dart
Declaring outputs for ids: 
[test_package|lib/test.dart]
Serving test_package web on http://localhost:8080
classifying test_package|web/test.dart
Applying transform to ids: 
[test_package|lib/test.dart, test_package|web/test.dart]
Build completed successfully
```

This time `declareOutputs` and `apply` only get called once, but when `declareOutputs` is called it is only given the files in `lib`. This means it could easily not be declaring the proper outputs.

**Comment by nex3** [comment]
The more I think about this, the more I think the current behavior is correct. It's pretty important for pub's architecture that it loads the lib/ directory first before web/ and/or test/. It's also important that it starts running transformers as soon as possible, to cut down on latency. Most of the time this doesn't produce any visible oddities, but when you specifically have an aggregate transformer that consumes everything in the package, it will get run twice because there are more assets being added to that environment over time.

It seems like the best thing to do here is to either make the transformer in question not consider `lib/` files to be primary inputs, or to add some checking to avoid printing warnings for entrypoints in directories that aren't loaded.

**Comment by jakemac53** [comment]
> It's pretty important for pub's architecture that it loads the lib/ directory first before web/ and/or test/. It's also important that it starts running transformers as soon as possible, to cut down on latency.

Since the primary inputs/ids are a stream anyways it should be possible to do this without re-invoking apply/declareOutputs?

Also today the inputs in lib will get processed twice, because they are provided to apply/declareOutputs twice.

> It seems like the best thing to do here is to either make the transformer in question not consider lib/ files to be primary inputs, or to add some checking to avoid printing warnings for entrypoints in directories that aren't loaded.

The transformer doesn't actually know if a particular folder just isn't being supplied right now, or is in fact empty. It is probably pretty safe to assume though that if no files were found in a folder that its just not being supplied right now.

**Comment by nex3** [comment]
> Since the primary inputs/ids are a stream anyways it should be possible to do this without re-invoking apply/declareOutputs?

Not really. At the point at which the lib files are added, neither pub nor barback have the context to know that there will be more assets coming. It would be a substantial refactor to add that context without breaking the ability of most transformers to start working early.

> Also today the inputs in lib will get processed twice, because they are provided to apply/declareOutputs twice.

As I said before, this is only true specifically for aggregate transformers that accept assets in lib/ as well as assets in test/ and/or web/.

> The transformer doesn't actually know if a particular folder just isn't being supplied right now, or is in fact empty. It is probably pretty safe to assume though that if no files were found in a folder that its just not being supplied right now.

Right. Also, why does a transformer looking for entrypoints mark files in lib/ as primary inputs in the first place, especially if the user doesn't list and entrypoints in lib/? Shouldn't it only mark files that are considered to be entrypoints as primary inputs?

**Comment by jakemac53** [comment]
>> Since the primary inputs/ids are a stream anyways it should be possible to do this without re-invoking apply/declareOutputs?

> Not really. At the point at which the lib files are added, neither pub nor barback have the context to know that there will be more assets coming. It would be a substantial refactor to add that context without breaking the ability of most transformers to start working early.

I am confused why it needs to close the stream and re-invoke apply/declarOutputs with a new stream later on as opposed to just leaving the original stream open and adding assets as they are found?

>> The transformer doesn't actually know if a particular folder just isn't being supplied right now, or is in fact empty. It is probably pretty safe to assume though that if no files were found in a folder that its just not being supplied right now.

> Right. Also, why does a transformer looking for entrypoints mark files in lib/ as primary inputs in the first place, especially if the user doesn't list and entrypoints in lib/? Shouldn't it only mark files that are considered to be entrypoints as primary inputs?

@eernstg for more insight here, I haven't looked deeply into the transformer implementation, but I would also expect only entry points to be primary inputs.

**Comment by nex3** [comment]
> I am confused why it needs to close the stream and re-invoke apply/declarOutputs with a new stream later on as opposed to just leaving the original stream open and adding assets as they are found?

For one thing, neither pub nor barback have the context to know that there will be more assets coming, so they wouldn't know to leave the stream open. For another, that's fundamentally not how Barback's API works; all the API expresses are what assets exist at any point in time, and the stream is created internally from that.

**Comment by eernstg** [comment]
On Thu, Jul 30, 2015 at 9:37 PM, Jacob MacDonald <notifications@github.com>
wrote:

> Since the primary inputs/ids are a stream anyways it should be possible to
> do this without re-invoking apply/declareOutputs?
>
> Not really. At the point at which the lib files are added, neither pub nor
> barback have the context to know that there will be more assets coming. It
> would be a substantial refactor to add that context without breaking the
> ability of most transformers to start working early.
>
> I am confused why it needs to close the stream and re-invoke
> apply/declarOutputs with a new stream later on as opposed to just leaving
> the original stream open and adding assets as they are found?
>
> The transformer doesn't actually know if a particular folder just isn't
> being supplied right now, or is in fact empty. It is probably pretty safe
> to assume though that if no files were found in a folder that its just not
> being supplied right now.
>
> Right. Also, why does a transformer looking for entrypoints mark files in
> lib/ as primary inputs in the first place, especially if the user doesn't
> list and entrypoints in lib/? Shouldn't it only mark files that are
> considered to be entrypoints as primary inputs?
>
> @eernstg <https://github.com/eernstg> for more insight here, I haven't
> looked deeply into the transformer implementation, but I would also expect
> only entry points to be primary inputs.
>
I guess it is implied that 'the transformer' is or at least could be the
reflectable transformer. From that point of view I can add some comments,
noting that I'm usually looking for insight on pub matters rather than
providing it. ;-)

Being a primary input is a barback concept. It provides a distinction
between the assets (typically disk files) used to bootstrap a build process
and the intermediary assets produced later in the build process. In
particular, it has nothing to do with a language compilation model, e.g.,
whether a given file contains a `main` function and is given as the sole
argument to a compiler that will subsequently use `import` directives etc.
to select other files.

Being an entry point for the reflectable transformer is a convention that
we have established: Users can specify a list of `entry_points` in
pubspec.yaml, and the reflectable transformer can read that list via the
given `BarbackSettings`. The semantics that we have chosen is as follows:

In the complete set of assets offered to the transformer, some assets will
be distinguished because they are intended to be the root of a program.
They would typically contain `main`, and they will typically be given as
the sole argument to a compilation. The analyzer will compute the
transitive closure of the import directives, hence allowing tools like the
transformer to work on the given set of assets "one program at a time". For
the reflectable transformer, an entry point is simply a program root
library, which must be transformed.

Any entry point which is received as an asset will be transformed (and the
transformation will access the complete import graph while doing that), and
nothing else will be transformed.

Note that even if we can iterate over each member A of the set of assets
offered, it is not sufficient for the transformation to know A and its
transitive import closure. This is because the transformation needs to
generate code that might differ for the same A, depending on which entry
point is considered as the program root. This means that we must insist on
knowing which libraries are considered to be entry points, and which ones
are not.

With that, there is certainly no reason to expect all assets to be entry
points, and there is no reason to expect `isPrimary` to imply that a given
asset is an entry point, nor that it isn't. These concepts are simply
unrelated.

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by jakemac53** [comment]
> With that, there is certainly no reason to expect `isPrimary` to imply that a given asset is an entry point, nor the converse. These concepts are simply unrelated.

It is the job of a transformer to decide what `isPrimary` means in its own context. The method is basically just a filter for the assets to provide directly to `apply`. In the context of the reflectable transformer (or most transformers doing whole program analysis), it makes sense to only supply entry points to the `apply` method. In fact the reflectable transformer itself is simply ignoring anything else that gets passed to apply as far as I can tell, and by only supplying the intended files in the first place you could implement two very simple but likely effective performance enhancements, in addition to any barback performance wins:

- It wouldn't need to [wait](https://github.com/dart-lang/reflectable/blob/master/reflectable/lib/src/transformer_implementation.dart#L1450) until all assets are ready before processing.
- It wouldn't have to [repeatedly](https://github.com/dart-lang/reflectable/blob/master/reflectable/lib/src/transformer_implementation.dart#L1461) search the entire assets list for entry points.

**Comment by eernstg** [comment]
On Fri, Jul 31, 2015 at 4:20 PM, Jacob MacDonald <notifications@github.com>
wrote:

> With that, there is certainly no reason to expect isPrimary to imply that
> a given asset is an entry point, nor the converse. These concepts are
> simply unrelated.
>
> It is the job of a transformer to decide what isPrimary means in its own
> context.
>
OK, the method `isPrimary` lets the transformer make that selection, but
the set of candidates for being a primary asset would still be chosen by
pub (or maybe barback), and the starting point for that would be things
like "all files in `test` including subdirectories" for an invocation like
`pub build test`. It doesn't have to be source code, so in general it's
very different from a notion such as our `entry_points`.

> The method is basically just a filter for the assets to provide directly
> to apply. In the context of the reflectable transformer (or most
> transformers doing whole program analysis), it makes sense to only supply
> entry points to the apply method.
>
We have been thinking about this in the following terms: It is not safe to
access disk files directly --- an asset may very well be an intermediate
result of transformation (by some other transformers running before this
one), so write and even read operations must be performed on `Asset`s, not
disk files. If we must obtain assets for everything we touch, anyway, there
wouldn't be much to gain from including just the entry points and rejecting
all other potential assets in `isPrimary`.

Note that we must in general visit all assets in the transitive import
closure of a given entry point, because any library could have a
@myReflectable annotation somewhere, which implies that some extra code
should be generated in order to provide the requested level of reflection
support.

Besides, I don't know for sure how/whether it would be possible to obtain
an asset out of the blue, if we have rejected it with `isPrimary` at first
and then later discover that we need it. Isn't the set of assets served by
'resolver.dart' with `getSourceAssetId` limited to the assets that were
declared primary? If there is another transformer running before this one,
and a non-entry-point library originates in a file 'some/path/foo.dart' but
has been transformed and should be accessed via an in-memory `StringAsset`,
can we rely on 'resolver.dart' to find that string asset rather than going
back to the (now obsolete) disk file and creating a new `FileAsset`?

> In fact the reflectable transformer itself is simply ignoring anything
> else that gets passed to apply as far as I can tell,
>
Not quite. For instance, we obtain an `AssetId` for the library where a
problem is detected in `_warn`. It would be a quite typical situation that
the subclass of `Reflectable` which is used to specify a mirror system
(often named `MyReflectable` in our examples) would be declared in some
other file than an entry point, e.g., because it is being reused by several
entry points. That's a concrete use case for a non-entry-point asset.

> and by only supplying the intended files in the first place you could
> implement two very simple but likely effective performance enhancements, in
> addition to any barback performance wins:
>
>    - It wouldn't need to wait
>    <https://github.com/dart-lang/reflectable/blob/master/reflectable/lib/src/transformer_implementation.dart#L1450>
>    until all assets are ready before processing.
>    - It wouldn't have to repeatedly
>    <https://github.com/dart-lang/reflectable/blob/master/reflectable/lib/src/transformer_implementation.dart#L1461>
>    search the entire assets list for entry points.
>
> Thanks for the pointers, noted them!

Do you think that `await aggregateTransform.primaryInputs.toList();` causes
a significant delay? The benefit we would have if we could reduce the
primary inputs to entry-points-only would be that all other assets would be
created later, "lazily", as we work on each entry point and its import
closure.

For the mapping of entry points to assets we would get a shorter `assets`
list, and we could iterate over `assets` and use binary search in (a sorted
variant of) `entryPoints`, which would reduce the complexity from O(#assets
* #entryPoints) to O(#assets * log(#entryPoints)). I don't know if the
numbers involved are large enough to make that significant, but it
shouldn't hurt to do it.

But we do need to know that the transitive import closure of any given
asset is available, even if we discard all non-entry-point assets at first
by declaring them 'not primary'. If we suddenly get correctness issues
because some setup uses multiple transformers with reflectable in a
non-first position then it's a bad trade-off. ;-)

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by jakemac53** [comment]
> Besides, I don't know for sure how/whether it would be possible to obtain
an asset out of the blue, if we have rejected it with `isPrimary` at first
and then later discover that we need it. Isn't the set of assets served by
'resolver.dart' with `getSourceAssetId` limited to the assets that were
declared primary?

I think maybe this is a core point of confusion. Regardless of what assets are marked as `primary`, ALL assets are available via the [readInput](http://www.dartdocs.org/documentation/barback/0.15.2+6/index.html#barback/barback.AggregateTransform@id_readInput) and [readInputAsString](http://www.dartdocs.org/documentation/barback/0.15.2+6/index.html#barback/barback.AggregateTransform@id_readInputAsString) methods. The `primary` inputs are usually just the ones that you want to use as a starting point.

**Comment by jakemac53** [comment]
> Do you think that `await aggregateTransform.primaryInputs.toList();` causes
a significant delay? The benefit we would have if we could reduce the
primary inputs to entry-points-only would be that all other assets would be
created later, "lazily", as we work on each entry point and its import
closure.

Yes, I do think this would help, but I don't have any actual data on it so that's just an assumption.

> But we do need to know that the transitive import closure of any given
asset is available, even if we discard all non-entry-point assets at first
by declaring them 'not primary'. If we suddenly get correctness issues
because some setup uses multiple transformers with reflectable in a
non-first position then it's a bad trade-off. ;-)

I answered this with my first response, but yes all assets will be available, including ones created by other transformers.

**Comment by eernstg** [comment]
OK, very good! Then we'll mark all assets which are not entry points as not
primary.

On Fri, Jul 31, 2015 at 6:15 PM, Jacob MacDonald <notifications@github.com>
wrote:

> Do you think that await aggregateTransform.primaryInputs.toList(); causes
> a significant delay? The benefit we would have if we could reduce the
> primary inputs to entry-points-only would be that all other assets would be
> created later, "lazily", as we work on each entry point and its import
> closure.
>
> Yes, I do think this would help, but I don't have any actual data on it so
> that's just an assumption.
>
> But we do need to know that the transitive import closure of any given
> asset is available, even if we discard all non-entry-point assets at first
> by declaring them 'not primary'. If we suddenly get correctness issues
> because some setup uses multiple transformers with reflectable in a
> non-first position then it's a bad trade-off. ;-)
>
> I answered this with my first response, but yes all assets will be
> available, including ones created by other transformers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/pub/issues/1308#issuecomment-126737734>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984
