### ISSUE TITLE
1.12.0-dev.5.9 cannot publish because it can't find pubspec.yaml

### ISSUE THREAD

**Issue by abarth** [dart-lang/pub#1321]
When trying to publish the `sky_engine` package, I hit the following error with `pub` version 1.12.0-dev.5.9:

```
Publishing sky_engine 0.0.13 to https://pub.dartlang.org:
Uploading... (1.2s) 
Invalid upload: no pubspec.yaml file.
```

There did appear to be a `pubspec.yaml` file and publishing with version pub version 1.12.0-dev.3.1 worked.

**Comment by sethladd** [comment]
Any chance you can try dev.5.10 ?

Can you paste in the results of `ls -lR` ?

**Comment by abarth** [comment]
```
.:
total 28
drwxr-x--- 2 abarth eng 4096 Aug 25 09:50 apks
-rw-r----- 1 abarth eng  220 Aug 12 14:51 AUTHORS
-rw-r----- 1 abarth eng    0 Aug 25 10:12 foo.txt
drwxr-x--- 2 abarth eng 4096 Aug 25 09:59 lib
-rw-r----- 1 abarth eng 1559 Aug 12 14:51 LICENSE
-rw-r----- 1 abarth eng  297 Aug 25 09:36 pubspec.yaml
-rw-r----- 1 abarth eng  258 Jul 23 14:19 README.md
drwxr-x--- 2 abarth eng 4096 Aug 25 09:50 sdk_ext

./apks:
total 7396
-rw-r----- 1 abarth eng 7570488 Aug 25 09:50 SkyShell.apk

./lib:
total 8
-rw-r----- 1 abarth eng  40 Aug 25 09:59 REVISION
-rw-r----- 1 abarth eng 166 Aug 25 09:50 _sdkext

./sdk_ext:
total 308
-rw-r----- 1 abarth eng  457 Aug 25 09:49 Attr.dart
-rw-r----- 1 abarth eng 1456 Jul 16 12:20 builtin_natives.dart
-rw-r----- 1 abarth eng 2869 Aug 25 09:49 Canvas.dart
-rw-r----- 1 abarth eng  984 Aug 25 09:49 CharacterData.dart
-rw-r----- 1 abarth eng  695 Aug 25 09:49 ClientRect.dart
-rw-r----- 1 abarth eng  499 Aug 25 09:49 ClientRectList.dart
-rw-r----- 1 abarth eng  560 Aug 25 09:49 ColorFilter.dart
-rw-r----- 1 abarth eng  432 Aug 25 09:49 CSS.dart
-rw-r----- 1 abarth eng  650 Aug 25 09:49 CSSStyleDeclaration.dart
-rw-r----- 1 abarth eng 1234 Aug 12 14:51 CustomColor.dart
-rw-r----- 1 abarth eng  520 Aug 12 14:51 CustomColorFilter.dart
-rw-r----- 1 abarth eng  845 Aug 12 14:51 CustomDrawLooperLayerInfo.dart
-rw-r----- 1 abarth eng  383 Aug 12 14:51 CustomFilterQuality.dart
-rw-r----- 1 abarth eng 2102 Aug 12 14:51 CustomGradient.dart
-rw-r----- 1 abarth eng 1035 Aug 12 14:51 CustomMaskFilter.dart
-rw-r----- 1 abarth eng 1001 Aug 12 14:51 CustomOffsetBase.dart
-rw-r----- 1 abarth eng 1644 Aug 12 14:51 CustomOffset.dart
-rw-r----- 1 abarth eng 1768 Aug 19 13:06 CustomPaint.dart
-rw-r----- 1 abarth eng  372 Aug 12 14:51 CustomPaintingStyle.dart
-rw-r----- 1 abarth eng 1002 Aug 12 14:51 CustomPoint.dart
-rw-r----- 1 abarth eng 2399 Aug 19 13:06 CustomRect.dart
-rw-r----- 1 abarth eng  567 Aug 12 14:51 CustomRSTransform.dart
-rw-r----- 1 abarth eng 2169 Aug 12 14:51 CustomSize.dart
-rw-r----- 1 abarth eng  881 Aug 20 15:49 CustomTransferMode.dart
-rw-r----- 1 abarth eng 2347 Aug 25 09:49 dart_sky.dart
-rw-r----- 1 abarth eng 1607 Aug 25 09:49 Document.dart
-rw-r----- 1 abarth eng  455 Aug 25 09:49 DocumentFragment.dart
-rw-r----- 1 abarth eng  636 Aug 25 09:49 DOMError.dart
-rw-r----- 1 abarth eng  600 Aug 25 09:49 DOMException.dart
-rw-r----- 1 abarth eng  883 Aug 25 09:49 DOMTokenList.dart
-rw-r----- 1 abarth eng  445 Aug 25 09:49 Drawable.dart
-rw-r----- 1 abarth eng  367 Aug 25 09:49 DrawLooper.dart
-rw-r----- 1 abarth eng  849 Aug 25 09:49 DrawLooperLayerInfo.dart
-rw-r----- 1 abarth eng 2732 Aug 25 09:49 Element.dart
-rw-r----- 1 abarth eng  574 Aug 25 09:49 ErrorEvent.dart
-rw-r----- 1 abarth eng  267 Aug 25 09:49 EventCallback.dart
-rw-r----- 1 abarth eng 1408 Aug 25 09:49 Event.dart
-rw-r----- 1 abarth eng  274 Aug 25 09:49 FrameCallback.dart
-rw-r----- 1 abarth eng  752 Aug 25 09:49 GestureEvent.dart
-rw-r----- 1 abarth eng  738 Aug 25 09:49 Gradient.dart
-rw-r----- 1 abarth eng  351 Aug 25 09:49 HTMLElement.dart
-rw-r----- 1 abarth eng  541 Aug 25 09:49 Image.dart
-rw-r----- 1 abarth eng  616 Aug 25 09:49 ImageData.dart
-rw-r----- 1 abarth eng  275 Aug 25 09:49 ImageDecoderCallback.dart
-rw-r----- 1 abarth eng  570 Aug 25 09:49 ImageDecoder.dart
-rw-r----- 1 abarth eng  825 Aug 25 09:49 KeyboardEvent.dart
-rw-r----- 1 abarth eng  685 Aug 25 09:49 LayerDrawLooperBuilder.dart
-rw-r----- 1 abarth eng 1273 Aug 25 09:49 LayoutRoot.dart
-rw-r----- 1 abarth eng  549 Aug 25 09:49 MaskFilter.dart
-rw-r----- 1 abarth eng  491 Aug 25 09:49 MediaQueryList.dart
-rw-r----- 1 abarth eng  487 Aug 25 09:49 MediaQueryListEvent.dart
-rw-r----- 1 abarth eng  603 Aug 25 09:49 MutationObserver.dart
-rw-r----- 1 abarth eng  919 Aug 25 09:49 MutationRecord.dart
-rw-r----- 1 abarth eng 1313 Aug 25 09:49 Node.dart
-rw-r----- 1 abarth eng  475 Aug 25 09:49 NodeList.dart
-rw-r----- 1 abarth eng  427 Aug 25 09:49 PageTransitionEvent.dart
-rw-r----- 1 abarth eng  648 Aug 25 09:49 PaintingNode.dart
-rw-r----- 1 abarth eng 1490 Aug 25 09:49 ParentNode.dart
-rw-r----- 1 abarth eng  795 Aug 25 09:49 Path.dart
-rw-r----- 1 abarth eng  433 Aug 25 09:49 Picture.dart
-rw-r----- 1 abarth eng  716 Aug 25 09:49 PictureRecorder.dart
-rw-r----- 1 abarth eng 1814 Aug 25 09:49 PointerEvent.dart
-rw-r----- 1 abarth eng 2601 Aug 25 09:49 Range.dart
-rw-r----- 1 abarth eng  290 Aug 25 09:49 RequestAnimationFrameCallback.dart
-rw-r----- 1 abarth eng  536 Aug 25 09:49 RRect.dart
-rw-r----- 1 abarth eng  363 Aug 25 09:49 Shader.dart
-rw-r----- 1 abarth eng  645 Jul 16 12:20 sky_internals.dart
-rw-r----- 1 abarth eng  415 Aug 25 09:49 Text.dart
-rw-r----- 1 abarth eng  589 Aug 25 09:49 TextEvent.dart
-rw-r----- 1 abarth eng 1358 Aug 25 09:49 TextMetrics.dart
-rw-r----- 1 abarth eng  569 Aug 25 09:49 Tracing.dart
-rw-r----- 1 abarth eng  968 Aug 25 09:49 UIEvent.dart
-rw-r----- 1 abarth eng 1726 Aug 25 09:49 URL.dart
-rw-r----- 1 abarth eng 1253 Aug 25 09:49 View.dart
-rw-r----- 1 abarth eng  255 Aug 25 09:49 VoidCallback.dart
-rw-r----- 1 abarth eng  560 Aug 25 09:49 WheelEvent.dart
-rw-r----- 1 abarth eng 1767 Aug 25 09:49 Window.dart
```

**Comment by abarth** [comment]
I can try dev.5.10 next time I need to publish the package.

**Comment by sethladd** [comment]
Thanks! Just to check, are you running pub from that directory?

**Comment by abarth** [comment]
Yes.  I've got a script that automates the process, which worked with previous versions of `pub` (and worked after I downgraded `pub`).  Also, I ran the `pub` command manually from that directory to be sure.

**Comment by nex3** [comment]
As far as I can tell from inspecting the intermediate tarballs in the publish tests, they do contain all the files I expect, including the pubspec. I'm curious to see what happens if you try to upload a different package, or with a different dev version. I've also filed dart-lang/pub-dartlang-dart#36 to track creating a development database that can be used to test issues like this without modifying the production package server.

I'm not sure what changes between those two versions would have triggered this. [Here's the whole pub history between them](https://github.com/dart-lang/pub/compare/072c5d85f4741bd4eede3eb8d309669b887e3c54...d90268693d1a9dbe5ea11cd9c80b842e3bf1581c); the only change to the publishing code is making it not time out.

**Comment by mkustermann** [comment]
@abarth / @nex3 

It should be pretty easy to compare whether the two tarballs are different, you can use a local pub server, something like this:

```
$ git clone https://github.com/dart-lang/pub_server.git
$ cd pub_server
pub_server $ pub get
pub_server $ dart example/server.dart
Listening on http://localhost:8080

To make the pub client use this repository configure your shell via:

    $ export PUB_HOSTED_URL=http://localhost:8080
```

Publish using the two different pub clients
```
$ export PUB_HOSTED_URL=http://localhost:8080
$ cd sky_engine
sky_engine $ ~/Downloads/dart-sdk-old/bin/pub publish
sky_engine $ vim pubspec.yaml
> change version number
sky_engine $ ~/Downloads/dart-sdk-new/bin/pub publish
```

Afterwards the tarball contents can be compared:

```
pub_server $ tar '--exclude=*/*/*' -tzf pub_server-repository-data/sky_engine/<version-1>/package.tar.gz
pubspec.yaml
...
pub_server $ tar '--exclude=*/*/*' -tzf pub_server-repository-data/sky_engine/<version-2>/package.tar.gz
pubspec.yaml
...
```

**Comment by abarth** [comment]
Issue still occurs with Pub 1.12.0-dev.5.10

**Comment by nex3** [comment]
I just successfully published a package with 1.13.0-edge.84a3560d0e3c4bbb99b135404c015232a204b00f, which should use the same version of pub as the latest dev branch.

**Comment by mkustermann** [comment]
@nweiz @munificent 

So this is for sure a bug in the pub client. I managed to debug this issue now. What happens is that  sky does not follow the standard conventions of having a repository where the pub package reside in. What rather happens is that the pub packages **get generated** via a build process. These generated pub packages reside afterwards in `out/.../packages/sky_engine/sky_engine`.

The second aspect is that the sky git repository has a `.gitignore` at the root, which - for obvious reasons - includes the `out/` directory.

Now since the [sdk roll](https://github.com/dart-lang/sdk/commit/b47940fb822863353ecc548858c886667d3c7c40) a new "feature" is included in pub, introduced by this [pub commit](https://github.com/dart-lang/pub/commit/2bd839fe7f271eb78b7f12efd4e4b11a697ae98d), which seems to respect `.gitignore` not just in the package root but also in directories further up the hierarchy. Therefore it seems to ignore all files and in fact uploads an empty package (can be reproduced with instructions I gave earlier).

* So the main issue here is that pub seems to do the validation if a package can be published not based on the pruned list of files. So it should first respect `.gitignore` and then look if the remaining files contain `pubspec.yaml`, `LICENSE` ...

* Additionally, for use cases like sky, it should be possible to opt out of this "respect any .gitignore file up the directory hierarchy" behavior.

**Comment by nex3** [comment]
Thanks for tracking this down, Martin!

I've got two CLs out to address this. [One of them](https://codereview.chromium.org/1310253007/) makes package validation `.gitignore`-aware, so warnings reflect the actual uploaded state of the package; [the other](https://codereview.chromium.org/1317043002/) causes pub not to use `.gitignore` when the root of the package is itself ignored.

**Comment by ricowind** [comment]
@whesse @mit-mit 
Should this be considered for a stable patch release?

**Comment by nex3** [comment]
I was going to submit a merge request for this.

**Comment by dgrove** [comment]
my 2c: this should be a patch to stable after the release goes out.
