### ISSUE TITLE
Enable pub serve to work without a packages/ directory

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1331]
We believe that if the packages/ directory of symlinks was removed, that `pub serve` would stop working.

This is a tracking bug to ensure that `pub serve` works, even if there isn't a packages/ directory.

(this issue is part of "Eliminating symlinks, phase two" https://github.com/dart-lang/sdk/issues/24112)

**Comment by nex3** [comment]
> We believe that if the packages/ directory of symlinks was removed, that `pub serve` would stop working.

I'm not sure where this is coming from (probably me saying something confusing), but `pub serve` doesn't rely on symlinks at all, and never has. The server automatically serves requests including `/packages/` based on its internal knowledge of the package graph, without any reference to a `packages/` directory that may or may not exist on the filesystem.

**Comment by sethladd** [comment]
Ah, thanks for the clarification! Great to know.

(if there are specific cases where pub will break if there isn't a packages/ dir, can you please point me to those issues so we can track? Thanks!)

**Comment by nex3** [comment]
Other than `pub run` (which has since been updated), pub existed purely as a generator of the `packages/` directory, not as a consumer, so there aren't any cases where it itself will break if the directory stops being generated. There are plenty of cases where *users* of pub could break, but that's already being (more or less) tracked by e.g. dart-lang/test#327.

**Comment by sethladd** [comment]
Thanks @nex3 !
