### ISSUE TITLE
'pub serve' fails when pubspec.lock has changed

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1343]
_From @johnpryan on October 14, 2015 14:39_

When the pubspec.lock file changes, 'pub serve' fails:

```
The pubspec.lock file has changed since the .packages file was generated, please run "pub get" aga
in.
```

This requires users to run `pub get` and then `pub serve` again.  A workaround is to alias `pub get && pub serve` to `pub serve`

Is this intentional?

_Copied from original issue: dart-lang/sdk#24589_

**Comment by floitschG** [comment]
_From @zoechi on October 14, 2015 15:16_

This is intentional to not run `pub serve` on outdated dependencies. There was a change recently that this message is only shown when actually dependencies (or version constraints)  were changed but not for transformer config or similar unrelated changes.

**Comment by floitschG** [comment]
_From @johnpryan on October 14, 2015 16:32_

I agree running `pub serve` on outdated dependencies is bad, but is there a reason pub wouldn't attempt to update the dependencies automatically anymore?

**Comment by floitschG** [comment]
_From @zoechi on October 14, 2015 17:37_

I haven't seen doing it in the past. 
This issue should be moved to the pub repository.

**Comment by nex3** [comment]
This was intentionally changed in 1.12; you can always check for those in [the SDK changelog](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#tool-changes-1). We made this change because we decided that it was unintuitive for commands that have nothing to do with dependency management to do so implicitly (and potentially destructively). It was a particular problem for `pub run`, where an implicit `pub get` could just look like an executable being super slow.

**Comment by johnpryan** [comment]
Thanks for the clarification!
