### ISSUE TITLE
Unclear why user can't install specific package version

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1355]
Hi, filing this on behalf of a few users that ran into this yesterday in our hackathon (and coincidentally, engineers not at the hackathon).

Consider this scenario:

* I have dart SDK 1.13.0-dev.4 installed
* A version of sky_tools 0.0.30 exists in pub.dartlang.org: https://pub.dartlang.org/packages/sky_tools
* My pubspec.yaml explicitly says I have a dependency on "sky_tools: 0.0.30"
* I run `pub get`

Here's the output:

```
~/tmp/test2 $ pub get
Resolving dependencies... (1.0s) 
Package sky_tools has no versions that match 0.0.30 derived from:
- test2 depends on version 0.0.30
```

This was a real stumper for our users. Notice how pub says "no versions match 0.0.30" which is really weird because pub.dartlang.org clearly says there is a 0.0.30 that exists.

After a lot of debugging, turns out, that sky_tools has an SDK constraint:

```
"environment": {
        "sdk": ">=1.13.0-dev.7.4 <2.0.0"
      },
```

Ah ha! That explains it. :)

The feedback I received was "pub isn't telling me that my SDK is too new/old for the version of the package that I want, and the feedback is confusing because 0.0.30 does exists"

(FWIW we also ran with `pub --verbose get` and tried to look for a signal that the SDK version and constraint was the issue, but we didn't find that hint)

May we ask for more explanation when pub isn't able to install a specific version of a package because of an SDK constraint? That would be a big help, as we help our developers stay updated in our fast-moving world.

Thanks!

**Comment by sethladd** [comment]
cc @jamesr

**Comment by zoechi** [comment]
dup of #1318 -> #912

**Comment by sethladd** [comment]
Thanks. I'm not sure it's a dupe of #912 but does look similar to #1318.

**Comment by nex3** [comment]
It's definitely #912—that's the bug for the version solver not providing enough information in any context.

**Comment by sethladd** [comment]
It looks like #912 is scary and the last comment was "we don't have immediate plans to try to solve it " which concerns us. Would it possible to tease apart a few things we can do to help our users in the meantime?

What's a good way for us to make progress on #912 , especially when we have a couple of concrete cases that seem like good first steps?

**Comment by nex3** [comment]
This isn't something that's likely to be solvable incrementally. Because it works on such a difficult problem, the version solver is quite complicated and would probably require another substantial refactor to get the information we want out of it. I have some ideas for this refactor that I think are promising, but it'll probably take at least a month of dedicated work to get it in place, and that time hasn't been budgeted.

I'm happy to do that work. I agree this is a serious issue that needs to be addressed. But over the past couple quarters it's been lower-priority than a number of other long-term issues. If I make enough progress on the test package in Q4, I'll talk to Dan about getting this into my OKRs for Q1.

**Comment by jamesr** [comment]
A specific issue for sdk version failures is that verbosity=solver does not even mention packages with sdk mismatches in its output.  With package failures the verbosity=solver output is not very helpful but at least it exists in some form. If the verbose solver output said explicitly that is was rejecting packages due to sdk version it would have helped a bit in this failure.
