### ISSUE TITLE
Ability to express version constraints on packages that you do not depend upon

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1356]
_From @johnmccutchan on November 2, 2015 20:52_

It would be useful if you could express a version constraint on a package that you don't directly depend upon.

_Copied from original issue: dart-lang/sdk#24800_

**Comment by sethladd** [comment]
Detailing a scenario here might help.

Regardless, we should move this to the pub issue tracker.

**Comment by sethladd** [comment]
_From @johnmccutchan on November 2, 2015 20:52_

This version constraint would interact with any of your transitive dependencies or if your package itself is being consumed by another package.

**Comment by nex3** [comment]
What's the goal here? As Seth said, an example use-case would be helpful.

**Comment by Hixie** [comment]
The specific case that came up here is that sky_tools depends on test which depends on analyzer which in some versions imports dart:profiler and in others imports dart:developer.
sky_tools doesn't need analyzer, but uses an SDK that is incompatible with the version of analyzer that imports dart:profiler. So it needs to say that if you use analyzer, you have to use the versions that import dart:developer.

The real problem is that 'analyzer' doesn't know that some SDKs aren't compatible with some of its versions.

**Comment by sethladd** [comment]
What version of test did sky_tools depend on? And did sky_tools have an SDK constraint? And what version of Dart SDK are you using on your machine, and on Travis (or, your build system)?

**Comment by Hixie** [comment]
sky_tools does have an SDK constraint.
You can see the history of what sky_tools depended on here: https://github.com/flutter/tools/commits/master/pubspec.yaml
Pretty sure every SDK you can imagine is being used by the various people who were bit by this. (The workaround was for them to use 'pub upgrade' instead of 'pub get'.)

**Comment by nex3** [comment]
That problem is caused by entities (in this case the SDK itself) behaving badly and not respecting semantic versioning, which isn't a situation for which I want to add an entirely new versioning structure.

There are a couple other solutions I can see for the underlying issue:

- Add a feature to pub.dartlang.org to retroactively add additional constraints to a package. This would be generally useful, but it would probably be a lot of engineering effort that I'm not sure the pub.dartlang.org team has time for.

- Avoid making the breaking change in the first place. I've filed dart-lang/sdk#24803 to track this.
