### ISSUE TITLE
Allow environment variables in pubspec.yaml

### ISSUE THREAD

**Issue by afandria** [dart-lang/pub#1358]
Currently, when a path needs to be specified, it isn't possible to use environment variables. This leads to a number of `../../..` to be added to `pubspec.yaml`.  However, the exact local path provided will inherently vary from machine to machine, so the path checked into code may not always work for one's collaborators.

I have seen this issue arise when adding a `dependency_overrides` path for [Mojo](https://github.com/domokit/mojo) as well as when specifying a path-based dependency for the [flutter package](http://flutter.io/).

It would be very helpful if environment variables can be used in `pubspec.yaml`, so please consider adding it.

**Comment by nex3** [comment]
As a rule of thumb, path dependencies should be considered to be inherently machine-local. There are some exceptions to this—relative paths that are all contained within a single repository, for example—but for the most part, paths are contingent on the operating system and peoples' individual setups. They should be avoided in favor of hosted or Git dependencies when collaborating unless you can provide strong guarantees about the relative locations of packages, as in the single-repo example.

About environment variables in particular, there are a number of issues. First, it's backwards-incompatible—on Unix, all characters other than `/` are valid, so there's no way to add this without risking breakage. It also violates the idea of `pub get` being the only setup users need to get their package ready, since users would need to specify environment variables in order for the pubspec to be valid at all.  And it would be a hidden trap for people who are transitively using your package, who may have no idea what the semantics of the variable are in the first place or how to set it.

**Comment by afandria** [comment]
I understand how the Git dependency would work in many cases, but that makes it difficult for me and my collaborators to modify files from that dependency at the same time they make changes to the current project. My application spans multiple repositories, not all of which are owned by me.

I think the main issue is that my project and the dependent projects are under development, and `pub` does not support that use-case very well. Bugs and features can span projects. I need a pubspec.yaml file that allows me to change my code as well as my dependency's together. An environment variable solves that. I do not want to resort to generating my `pubsec.yaml` file with a script.

`$` is not a common choice of Unix file paths, and use of paths to specify a package should already be quite rare in `pubspec.yaml`. I don't believe that backwards incompatibility invalidates this need.

I do, however, like your invariant for the `pub get` command. Since `pub get` should make the setup package ready, then all we need to add is a mechanism to add transformations to `pub get` and `pub upgrade`. This will allow the environment variables to be substituted.

I don't accept the hidden trap argument. These transformations are not necessary beyond the development phase of these projects. Once the application is more stable (or complete), it would normalize its dependencies on pub, so there would be no trap to real end users.

Is modifying `pub get` feasible?

This is actually a dupe of https://github.com/dart-lang/pub/issues/798, which was originally submitted about 2 years ago. I believe that many projects are running into this same issue and must resort to odd hacks and workarounds (such as generating `pubspec.yaml`). This is an opportunity for pub to better support cross-package development, so I highly encourage revisiting this issue.

**Comment by nex3** [comment]
I'm sympathetic to the need to do heavy development across many disjoint packages without any public releases, but please understand that this it's a complex and contingent use-case that's far removed from pub's primary purpose, which is to enable the sharing and distribution of Dart code. Because this use-case is inherently complex, it's also difficult to design a small set of features that addresses it everywhere—you personally may find environment variables would work well, but other teams would probably find them too onerous (they're a huge pain to set up on Windows, for example).

My suggestion would be to just have users include their own machine's paths in their pubspecs while doing active development. This is certainly effort, but it's not that much more effort than manually configuring environment variables, for example, and it fits well with existing infrastructure.

> This is actually a dupe of #798, which was originally submitted about 2 years ago.

That's actually a very different issue, although I can understand the confusion. Some Dart documentation uses the term "environment variables" to refer to constants that can be accessed from Dart code via constructors like `const bool.fromEnvironment`. Those "environment variables" are entirely different than the operating system's notion of environment variables.

**Comment by nivisi** [comment]
Hey there! @nex3 not sure if someone still monitors this issue, perhaps you can redirect this question to someone else from the team.

I would like to suggest reviewing this feature, since it is not only related to local paths, but also to accessing remote packages. 

Use case: our application uses multiple 3rd party modules developed by other vendors, and our team does not have direct access to the source code repositories. We can't be invited to the repos either due to security restrictions. So we get access to those packages through Access Tokens, for both Github and Gitlab.

Right now, we are forced to put these Tokens right in the `pubspec.yaml` file to be able to simply fetch dependencies to our local. To avoid this, we're considering building a custom script for generating a `pubspec.yaml` file (gitignored), using a `pubspec.yaml.template` (not gitignored), using an environment file (gitignored).

But I think this is something that should be built-in, if `pub get` allows to fetch dependencies from `ref`s.

**Comment by stan-at-work** [comment]
Can this be reconsidered and be reopened ?

**Comment by nivisi** [comment]
Just an update on my comment (https://github.com/dart-lang/pub/issues/1358#issuecomment-3043757984), we have built the pubspec templates system. Combined with VS Code's built-in shortcuts and commands, we're able to automate all the generation, so it (almost) feels as it did before. It's even integrated with `melos`.

Still feels like a workaround. I think this should be a part of Dart.

**Comment by stan-at-work** [comment]
We should je be able to set a environment variable using `env.`...

Example:

```
tools:
    path: env.tools_path

models:
    ref: env.models_path

```

**Comment by sigurdm** [comment]
I think for the git credential use case, those can be provided via a credential helper instead.

See https://git-scm.com/docs/gitcredentials
And for github you can use gh auth: https://cli.github.com/manual/gh_auth_setup-git

**Comment by sigurdm** [comment]
@stan-at-work not sure what you mean here? What are tools and models in the context of a pubspec.yaml? Do you want to set or read environment variables?

**Comment by stan-at-work** [comment]
> 
> @stan-at-work not sure what you mean here? What are tools and models in the context of a pubspec.yaml? Do you want to set or read environment variables?

Thats exacly what i want to do yes.
