### ISSUE TITLE
pub run test on 1.14.0-dev.1 throws too many files open errors

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1366]
_From @Andersmholmgren on December 6, 2015 6:3_

```
00:00 +0 ~7 -7: loading test/client/entity/take2/user_entity_test.dart
  Failed to load "test/client/entity/take2/user_entity_test.dart":
  Unable to spawn isolate: "package:collection/equality.dart": Error loading file:///Users/blah/dart/backlogio_acdart/gitbacklog_root/gissue_root/gissue_client/packages/collection/equality.dart:
    Cannot open file, path = '/Users/blah/dart/backlogio_acdart/gitbacklog_root/gissue_root/gissue_client/packages/collection/equality.dart' (OS Error: Too many open files, errno = 24)
  #0      _asyncLoadErrorCallback (dart:_builtin:147)
  #1      _asyncLoadError (dart:_builtin:559)
  #2      _handleLoaderReply (dart:_builtin:362)
  #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
00:00 +0 ~7 -7: loading test/client/entity/take2/backlog_entity_test.dart

````

If I switch back to 1.13.0-dev.7.12 the problem goes away

_Copied from original issue: dart-lang/sdk#25123_

**Comment by mkustermann** [comment]
This might actually be a VM issue we've also encountered. The spawning of isolates was until recently blocking (which is a problem in an event based system, since it could block the isolate for potentially a whole second). This was fixed by the VM team (see https://github.com/dart-lang/sdk/issues/24849).

The second part of https://github.com/dart-lang/sdk/issues/24849 is to not reload the sources when using `Isolate.spawn`, which hasn't been fixed yet.

=> So I suspect that pub launches multiple isolates in parallel, maybe from the same source and maybe also via `Isolate.spawnUri`. The first part (same source) is captured in https://github.com/dart-lang/sdk/issues/24849. The second part - namely spawning isolates from different source - could also cause the "run out of file descriptors" issue. That could be the case if the DartVM does not have a bound on the maximum number of parallel file loads during `Isolate.spawnUri`.

cc: @turnidge @a-siva Is there such a limit? If not, maybe one should be introduced?

Though, leaving this issue open, because it could also be that barback or other components in pub open too many files (i.e. have no maximum bound).

**Comment by iposva-google** [comment]
Based on the path of the user directory I am guessing this error happens on a Mac. In the default setup Mac OS X has a very low limit of the number file descriptors by default (256 on my Mac desktop compared to several thousand on my Linux desktop).
@Andersmholmgren would you mind running "ulimit -n" in your shell and report? Thanks!

**Comment by nex3** [comment]
I've moved this to dart-lang/test#373. @floitschG, for future reference, if someone files an issue with `pub run $executable`, it's probably about the executable rather than pub itself.
