### ISSUE TITLE
NPE from pub get

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#1412]
When running `pub get` on our bot, we saw a stack trace thrown from pub:

```
The null object does not have a getter '_doneFuture'.

NoSuchMethodError: method not found: '_doneFuture'
Receiver: null
Arguments: []
dart:async                                   _StreamController.close
package:pub/src/utils.dart 583               tee.<fn>
dart:async                                   _StreamController.close
package:pub/src/utils.dart 530               validateStream.<fn>
dart:async                                   _EventSinkWrapper.close
package:barback/src/utils/file_pool.dart 40  FilePool.openRead.<fn>.<fn>
```

More details here: https://build.chromium.org/p/client.flutter/builders/Linux/builds/786/steps/steps/logs/stdio.

This was intermittent - forcing a build on the bot didn't show the issue a 2nd time.

**Comment by nex3** [comment]
As far as I can tell, no pub code has ever included the code `_doneFuture`. It looks like something in `dart:async`. Since [the call on line 583](https://github.com/dart-lang/pub/blob/c1405b945c6d818c8cfe78334e8d4b11fd913103/lib/src/utils.dart#L583) isn't passing in any arguments, I can only assume that this isn't something we can fix in pub, so I'm going to redirect this to the SDK repo.

**Comment by nex3** [comment]
This issue was moved to dart-lang/sdk#26338
