### ISSUE TITLE
Allow overridden dev dependencies to be published

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#1444]
Currently, we don't allow packages that contain dependency overrides to be published. Normally, an override means that the developer is (maybe accidentally) using a different set of version constraints than the version they're trying to ship, which is bad (see #1256).

I think we should relax this slightly by allowing a package to be published with dependency overrides as long as all overridden packages also appear in `dev_dependencies` (we already have a check that ensures no packages appear as both dev and public dependencies). This will allow users to, for example, use an overridden test runner without having to delete the override to publish their package.

**Comment by zoechi** [comment]
Wouldn't it be better to address the underlying problem that dependencies relevant only for the user of a package and dependencies only relevant to the developer of the package are combined, while they should be split?

**Comment by nex3** [comment]
> Wouldn't it be better to address the underlying problem that dependencies relevant only for the user of a package and dependencies only relevant to the developer of the package are combined, while they should be split?

I'm not sure what you're proposing. As I see it, they are split—into dependencies on one hand and dev dependencies on the other.

**Comment by zoechi** [comment]
If I add `test` to `dev_dependencies` I can't have dependency versions for `lib` that are incompatible with one of the dependencies of `test`
In this simple case this might be unavoidable because how would I be able to test it otherwise.

But if I add `grinder` to `dev_dependencies` for build tasks (or similar) and `grinder` and `test` only agree on some older version of one or more dependencies that I depend on in `lib` then `dev_dependencies` limit what versions can be used during development, even though they don't limit the user of my package.

If I then add `polymer` for some example then I might introduce some additional conflicts in my dependency tree. 
There is no need at all for `tools`, `test`, `examples` to agree on a common set of dependencies. Each one only needs to agree with `lib` (for `tools` there is no need to agree with anything else in this example)

Using `dependency_overrides` is always a hack. There should be better ways.

**Comment by nex3** [comment]
I can certainly imagine a world where you separately specify the dependencies for each subtree of your application, but there are a lot of downsides. The UI would be much more complex, running `pub get` would take a lot longer, you'd run into problems with version skew between your separate dependency trees, and tools like `pub run` and the `test` package would have to have complex and likely-unintuitive logic for determining which dependency tree to use in which circumstance.

In general, the process of designing a system like pub is one of balancing the desire to do anything in any combination with the substantial benefits of simplicity. Striking this balance necessarily means that some things some people would like to do aren't possible, but if we made *everything* possible the system would be indistinguishable from manually having to write `.packages` files. The compromises we've struck give a lot of power, while preserving important invariants that make life much easier all around.

**Comment by zoechi** [comment]
It's just my opinion but I would find this much easier to understand than what one needs to know to resolve version conflicts

dependencies:
  lib:
    a
    b
    c
  tools:
    d
  test:
    lib # with whatever syntax to indicate the current project
    test
    mock
  example:
    lib
    e

This would make dev_dependencies obsolete

`pub upgrade` is usually quite fast but when I run into conflicts between d and e, the time I need to fix it usually takes more then all `pub get` and `pub upgrade` runs  for the previous year together.
Usually `pub get` or `pub upgrade` becomes notable slower with each added dependency.
I think in many projects, my proposal would make `pub upgrade` even faster.
