### ISSUE TITLE
'pub get' overwrites symlinked .packages file

### ISSUE THREAD

**Issue by yyoon** [dart-lang/pub#1493]
(moved from flutter/flutter#7296)

In fuchsia development setup, the `.packages` files are generated as part of fuchsia build and we create `.packages` file as a symbolic link to the fuchsia-generated `.packages` file, in order to make dart analysis work correctly with all the fuchsia dependencies.

The problem is that when we run `flutter packages get` (which shells out to `pub get`) when there is a symlinked `.packages` file in the directory, the tool overwrites the contents of the original file that the symlink points to, and this breaks any subsequent fuchsia build. The same happens when getting the packages as part of `flutter test`.

I think `pub get` should delete the existing .packages file (whether or not it is a symbolic link) and newly create one.

**Comment by nex3** [comment]
We're using the standard [`File.writeAsStringSync`](https://api.dartlang.org/stable/1.21.0/dart-io/File/writeAsStringSync.html) method. I suggest you file a bug against that.

**Comment by yyoon** [comment]
I don't know what exactly to file there, cause it seems like `File.writeAsStringSync` is doing the right thing according to its documentation, and it's a pretty generic method.

Wouldn't it make more sense to make `pub` code check to see if the existing `.packages` file is a symlink and unlink/delete it before writing the file?

**Comment by matanlurey** [comment]
I agree with @yyoon that pub needs to do work here.

(On a side note, please don't close bugs from Fuchsia prematurely)

**Comment by nex3** [comment]
@yyoon It seems like any time you'd want to express "write a file to disk overwriting whatever's there", you'd want to replace a symlink entirely rather than replacing the contents of its target. There's nothing special about `.packages` here other than that it's the example that this provoked this issue first. I don't want to replace all file writes across pub—not to mention the other tools I maintain—with "check if a symlink exists here, delete it if so, then write the file". This seems like a violation of user expectations in `dart:io`, so it should be fixed there.

@matanlurey What's wrong with closing an issue if I don't plan to take action on it? It doesn't close discussion; if I'm wrong and action needs to be taken, that can be discussed just as well with the issue closed as with it open.

**Comment by yyoon** [comment]
@nex3 

> It seems like any time you'd want to express "write a file to disk overwriting whatever's there", you'd want to replace a symlink entirely rather than replacing the contents of its target.

Personally, this isn't very obvious to me, and I think it could go either way as long as the behavior is clearly documented. According to the [`File` class doc](https://api.dartlang.org/stable/1.21.0/dart-io/File-class.html):
> If path is a symbolic link, rather than a file, then the methods of File operate on the ultimate target of the link, except for delete and deleteSync, which operate on the link.

Also, I was wary that changing its behavior might affect other third-party tools that rely on the current behavior.

Anyways, if you still think that replacing the entire symlink should be the default behavior, I'll go ahead and file an issue to the sdk repo (after you confirm).

**Comment by nex3** [comment]
> Personally, this isn't very obvious to me, and I think it could go either way as long as the behavior is clearly documented. According to the [`File` class doc](https://api.dartlang.org/stable/1.21.0/dart-io/File-class.html):
> > If path is a symbolic link, rather than a file, then the methods of File operate on the ultimate target of the link, except for delete and deleteSync, which operate on the link.

Hmm, I missed this documentation. This still seems unintuitive to me, but I doubt we'll be able to change the documented behavior, so I'll fix it in pub.

**Comment by yyoon** [comment]
That'd be great. Thanks!
