### ISSUE TITLE
Regression in SDK 1.22.0-dev.9.0: pub fails to start in checked mode

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/pub#1504]
This works:
```
[Dart SDK]\bin\dart.exe [Dart SDK]\bin\snapshots\pub.dart.snapshot
```
But this fails:
```
[Dart SDK]\bin\dart.exe  --checked [Dart SDK]\bin\snapshots\pub.dart.snapshot
```

The error is:
```
Wrong features in snapshot, expected 'release asserts type-checks x64-win' found 'release no-asserts no-type-checks x64-win'
```

OS: Windows 10, x64

**Comment by rmacnak-google** [comment]
The SDK now uses app snapshots instead of script snapshots, which include compiled code and must be run in the same mode that they were created. The SDK's snapshots should not be run directly, only through `dart-sdk/bin/pub`, which starts pub in production mode rather than checked mode. If you have some particular need to have pub run in checked mode, you should run it from source.

**Comment by alexander-doroshko** [comment]
@rmacnak-google Understood, thanks!

There's one unfortunate side effect, though. IntelliJ IDEA starts pub in checked mode when executing tests. There's no special reason for it, it just happened this way historically. For sure, I'll fix it tomorrow and update the Dart plugin. But users of older IDEs won't be able to run tests with SDK 1.22+ from the IDE.

**Comment by nex3** [comment]
As Ryan points out, you should only be running SDK executables through the provided scripts. If you're doing otherwise, you're out of supported territory.
