### ISSUE TITLE
SDK sources don't place nice with SDK upgrades

### ISSUE THREAD

**Issue by abarth** [dart-lang/pub#1519]
1. My package has an SDK dependency whose version gets written to the pubspec.lock file.
2. I update my SDK to a version that has a newer version of that package.
3. `pub get` gives me an error because it can't give me the version of the package that my pubspec.lock files says I should get (because it only has one choice---the one version in the SDK that doesn't match the pubspec.lock file).

@munificent says "I think it's probably reasonable for `pub get` to unlock the SDK dependency if it doesn't match in the same way that it unlocks regular dependencies if you change the pubspec and run `pub get` again."

@nex3  says "Yeah, this looks like a bug to me. Can you file an issue against `pub`?"

See https://github.com/flutter/flutter/issues/8336 for context.

Thanks!

**Comment by zoechi** [comment]
Isn't it the job of `pub upgrade` to unlock that scenario?

**Comment by abarth** [comment]
Yes, `pub upgrade` solves the problem.  One potential solution is that `pub get` could produce an error message that recommends running `pub upgrade` to get unstuck.  However, it's also possible that `pub get` could unstick you without requiring you to run an additional command, as per @munificent 's suggestion.

**Comment by zoechi** [comment]
> that pub get could produce an error message that recommends running pub upgrade to get unstuck

Good error messages are always great

> that pub get could unstick you without requiring you to run an additional command

I think if you just want up-to-date dependencies and ignore `pubspec.lock`, you shouldn't use `pub get` in the first place. 
The main problem is that `pub get` is promoted as the default option to fetch dependencies, while what probably most people want is what `pub upgrade` does. 

If `pub get` would automatically unstick, then you won't get an error message or any hint at all, when you actually want to get exactly that dependencies listed in `pubspec.lock`.
I think this is a great way to make people spend hours searching for the cause of some unexpected behavior caused by some "magic".

I'd even argue that `pub get` falling back to `pub upgrade` where there is not `pubspec.lock` is problematic. I think it would be better if it would just print an error that `pub get` can't be used without `pubspec.lock` and that `pub upgrade` should be used instead (wouldn't expect a change here though)

**Comment by abarth** [comment]
Do you feel the same way about the following scenario?

1. Write a pubspec.yaml that depends on version 1.0 of package X.
2. Run `pub get`
3. Edit pubspec.yaml to depend on version 2.0 of package X.
4. Run `pub get`

Specifically, your point of view seems to imply that step 4 should generate an error because `pub get` cannot get you the version of package X that's written in your pubspec.lock file (i.e., 1.0).

To me, that result seems user hostile in the same way that the experience in the original report is user hostile.

**Comment by zoechi** [comment]
I think you shouldn't have used `pub get` in the first place, but `pub upgrade` instead ;-)

`pub get` is (sadly besides others) to get exactly the dependencies specified in `pubspec.lock`, this is obviously not what you want, therefore I think you should change what you're doing, instead of changing `pub get` ;-)

If we want `pub get` to be the most common and convenient option that does what is usually right or usually what the user probably wants with all kind of convenient "magic", then perhaps adding another command that just fetches what is defined in `pubspec.lock` would be the way to go, to make `pub get` free to do whatever seems most convenient for the common case.

**Comment by abarth** [comment]
> [...] instead of changing `pub get`

My understanding is that `pub get` does not currently generate an error at step 4 of my previous comment but instead already does what I want.  The issue is about applying analogous behavior to packages that come from SDK sources.

**Comment by nex3** [comment]
@abarth You're right. `pub get` tries to respect `pubspec.lock` as much as possible, but it will make changes if a locked package isn't valid for whatever reason. The fact that it's not making changes here is a bug.
