### ISSUE TITLE
Handle timeouts

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/pub#1569]
Several times already a Travis-CI test has failed because of a pub timeout (e.g. https://travis-ci.org/eqdb/eqdb/jobs/222150265#L435). This seems like something that is not really supposed to happen (either pub should retry more times or the pub server must be scaled up).

**Comment by zoechi** [comment]
The linked build is successful. Can you link to the actual error message?

**Comment by hermanbergwerf** [comment]
Oh, I restarted it. I guess Travis reuses the same Id for the log :-(.
Sorry.

**Comment by hermanbergwerf** [comment]
I fear there is no way to get the log back. I usually restart a built when
it fails because of an external error so I couldn't find older logs either.
It happened a couple of times on my own machine as well not too long ago. I
believe the message was quite short ('connection timed out') and the exit
seemed pretty graceful.


I will report back to this issue if it happens again on Travis.

**Comment by kevmoo** [comment]
Duplicate of https://github.com/dart-lang/pub/issues/1556
