### ISSUE TITLE
pub upgrade fails in unhelpful ways when firewall restricts access to internet

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/pub#1591]
A Windows user reported in https://github.com/flutter/flutter/issues/9976 that `pub upgrade` failed with the following exception:

```
%1 is not a valid Win32 application.

  Command: C:\Users\[username]\flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz
```

As it turns out, his firewall was to restrictive and silently denied pub access to the internet. There should be a more descriptive error if pub cannot access the internet.

**Comment by nex3** [comment]
I'm not sure what we can do with obtuse OS error messages other than report what the OS tells us. I have no idea why Windows says something isn't a valid application because of a network issue, but I don't want to special-case this error message—what if this appears later as a legitimate error message? Or if it hides some other, different underlying issue?

**Comment by natebosch** [comment]
I don't have a windows box handy to test, but my first hunch would be this error happens if we ask 7zip to extract an empty file.

Will the `StreamedResponse.stream` be empty from 'httpClient.send(new http.Request("GET", url));` if a firewall blocked pub? We don't do any checking for that and we probably could

**Comment by nex3** [comment]
Oh, good point—we should be checking the status there.

**Comment by nex3** [comment]
Actually, it looks like automatically check the status for every request [here](https://github.com/dart-lang/pub/blob/12de2361a8870877b5c8aa4f184af21ae77a74ac/lib/src/http.dart#L93-L123). So if the firewall is blocking the request, it's doing so without providing an informative HTTP status code.

**Comment by natebosch** [comment]
Hmm, we just tested running `7za.exe e empty_file.tar.gz` and the error was `Error: cannot open archive` rather than what we see above, so my hunch was wrong.

As [this comment](https://github.com/flutter/flutter/issues/9976#issuecomment-301170152) points out the error points much more to a space in the path - can we consistently repro that situation?

It's possible we need to do some extra escaping before we try to run external programs on windows.

**Comment by goderbauer** [comment]
There is another user that saw the same exception when installing flutter: https://github.com/flutter/flutter/issues/15014

**Comment by sigurdm** [comment]
We no longer use 7zip. I think this is stale.

Closing
