### ISSUE TITLE
Add package features

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1593]
*Edited by @nex3*

I'm updating this to track progress on the package features feature I outlined below. In particular, we need:

* [x] The ability to declare and depend on off-by-default features.
* [x] The ability to declare on-by-default features, and to disable them.
* [x] The ability to declare SDK constraints in features.
* [x] The ability to depend on a feature if it's available, but allow versions of the package that don't expose it.
* [ ] The ability for one feature to depend on another in the same package.
* [x] The ability to enable or disable features in `pub global activate`.
* [x] Handle multiple dependencies on the same package with different features.
* [x] Ensuring that a package that exposes or uses features has an appropriate SDK constraint so it's not visible to older `pub` versions.

----

Rather, it should be possible to create a `local_storage` library with 3 implementations:

* Using `PlatformMessages` for `dart:ui` / Flutter
* Using `localStorage` for `dart:html`
* Using a data directory for `dart:io`

Today this doesn't really work, because I can't conditionally depend on the Flutter SDK. Might I suggest that we allow a dependency that itself depends on Flutter, even if we don't have the Flutter SDK installed?

/cc @jakemac53 who is working on pub these days.

**Comment by nex3** [comment]
This is definitely a hole in our current package story—one that'll take a lot of careful design to fix properly. My bet is that this will ultimately require some degree of language support to resolve, some way of determining at runtime what packages are available and in what form.

One idea for this that I've floated before is *package features* (which I totally stole from Rust): a package would be able to declare multiple optional "features", each of which has its own dependencies. Then dependencies on that package could declare which features they need, and only those dependencies would be included in the package graph. Something like:

```yaml
# local_storage/pubspec.yaml
features:
  flutter:
    platform_messages:
      version: ^1.2.0
      sdk: flutter
  io:
    path: ^1.4.0

# app/pubspec.yaml
dependencies:
  local_storage:
    version: ^1.0.0
    features: [flutter, io]
```

The trick is providing `local_storage` the ability to load flutter when flutter is running and to load IO otherwise, and more generally to be able to change its behavior based on which features were selected. Something like configuration-specific imports, combined with the ability for pub to define environment constants, could do this.

**Comment by matanlurey** [comment]
@nex3:

> This is definitely a hole in our current package story—one that'll take a lot of careful design to fix properly. My bet is that this will ultimately require some degree of language support to resolve, some way of determining at runtime what packages are available and in what form.

I imagine this is fixable at compile time, to some extent, right? I don't know what the full story is with the unified `front_end`, but does it know what the package graph is being built for (i.e. web, standalone vm, flutter)?

> 
> One idea for this that I've floated before is *package features* (which I totally stole from Rust): a package would be able to declare multiple optional "features", each of which has its own dependencies. Then dependencies on that package could declare which features they need, and only those dependencies would be included in the package graph. Something like:
> 
> ```yaml
> # local_storage/pubspec.yaml
> features:
>   flutter:
>     platform_messages:
>       version: ^1.2.0
>       sdk: flutter
>   io:
>     path: ^1.4.0
> 
> # app/pubspec.yaml
> dependencies:
>   local_storage:
>     version: ^1.0.0
>     features: [flutter, io]
> ```
> 
> The trick is providing `local_storage` the ability to load flutter when flutter is running and to load IO otherwise, and more generally to be able to change its behavior based on which features were selected. Something like configuration-specific imports, combined with the ability for pub to define environment constants, could do this.

I think this ~mostly works with configuration-specific imports, except that non-Flutter libs will blow up if they see `dart:ui`, and there is no way to ignore this.

Anyway, I think this is becoming very important, otherwise we risk a package ecosystem with lots of specialized packages that only help either web or flutter users, with no unified APIs or experience.

**Comment by nex3** [comment]
> I imagine this is fixable at compile time, to some extent, right? I don't know what the full story is with the unified `front_end`, but does it know what the package graph is being built for (i.e. web, standalone vm, flutter)?

Sorry, I should have been clearer—I meant "language time" (whether that's compile time or runtime), as opposed to "package resolution time". Anything that happens at language time, especially around imports, needs language support.

> edit: This would work if you could ignore the fact that `flutter` isn't resolvable.

Configuration-specific imports would do this, since they don't process any imports that are configured out.

> Anyway, I think this is becoming very important, otherwise we risk a package ecosystem with lots of specialized packages that only help either web or flutter users, with no unified APIs or experience.

Hear hear! I've been pushing for a language-level solution here for years, but I've had very little success getting momentum behind it. Configuration-specific imports made some progress, but they stalled out before they became widely usable.

**Comment by matanlurey** [comment]
I've started an internal thread to clarify the configuration-specific import story.

* If we decide to remove it, let's talk about separate entry-points w/o needing features
* If we decide to complete it, we'll still need `pub` not to blow up*

*Perhaps the error "The Flutter SDK is not available." could be instead:

```bash
> Resolving dependencies...
> Warning: The Flutter SDK is not available.
> You will not be able to import libraries that rely on this dependency.
```

**Comment by nex3** [comment]
I'm retargeting this to specifically focus on package features, which is how we plan to address this issue.
