### ISSUE TITLE
Inference for features (instead of only explicit) *or* tooling?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1660]
Thought I'd throw out this idea, since it would "play nicely" with what @jakemac53 has already done in pub to support DDC: implicit features based on convention of exposed files in the `lib/` directory. Assume the following `package:code_builder`, that has a structure of:

## Idea 1: Inferred Features

```
lib/
  src/**
  code_builder.dart
  testing.dart
```

I'd love to be able to declare in my `pubspec.yaml`:

```
features:
  - $lib

dependencies:
  analyzer:
  matcher:
```

Statically we can determine `lib/code_builder.dart` imports `analyzer` and `lib/testing.dart` imports `matcher`, so we can infer a (default) feature called `code_builder` and an (optional) feature called `testing`.

## Idea 2: Inferred Feature Use

In combination or standalone of idea 1 - inferred feature use. If I write my own package, and *don't* import `code_builder/testing.dart`, it can be inferred I am only relying on the default feature of code_builder, and I don't need `pkg/matcher` at all.

## Idea 3: No inference, but tooling

I.e. something like `pub features infer`, that will do either (1) or (2) _for_ me. Internally we have tools like `glaze` that do something like this for go users, and folks are really happy about it. It gives you lots of flexibility without explicit verbosity.

**Comment by natebosch** [comment]
Given that we need `pubspec.yaml` to be backwards and forwards compatible for long periods of time I think tooling is the safer place to start. I think this would be a really cool thing to have.

**Comment by jakemac53** [comment]
Ya I think tooling is probably ideal, but imo there is no reason for it to be part of pub. It can easily be a separate package which allows it to have breaking changes etc.

**Comment by matanlurey** [comment]
Sure, but if pub doesn't use the same algorithm it is sort of moot, right?

**Comment by jakemac53** [comment]
Not sure what you mean exactly... to clarify I was implying a tool which has two commands:

- One that creates a `features` section in your pubspec.yaml based on your package layout.
- Another one that can modify your deps in your pubspec.yaml to only depend on the features you actually use.

**Comment by jakemac53** [comment]
One difficult thing I think might be version constraints, I don't know how that works with features in general though.

**Comment by matanlurey** [comment]
Oh ok yeah, if this is just a tool, then yeah it can live separate. At the same time, if you look at how `npm` is evolving, they are adding more and more first-party features to _avoid_ having lots of duplicate functionality. But YMMV.

**Comment by nex3** [comment]
If we make this a tool, we need to add a big bold warning that it's not going to be complete. There are a number of situations where just looking at imports won't give a complete idea of a library's dependencies. If you use an API from a package, you need to have a dependency on that package, even if you're not the one to import it—for example, if you use the `StreamChannel` returned by [`spawnHybridUri`](https://www.dartdocs.org/documentation/test/0.12.22+2/test/spawnHybridUri.html) in `test`. More generally, you may even need a dependency for a package whose Dart API you don't interact with at all, e.g. if you're invoking an executable or loading an asset.

I'm going to close this out since it looks like the plan is to create a separate tool for now.
