### ISSUE TITLE
What is the best way to tell whether `pub get` needs running for a project?

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#1678]
I'd like to detect when a user opens a project in Dart Code that is missing packages (eg. it's a fresh clone and they've never run `pub get`) and prompt them, with an easy button to do it (since otherwise they'll get a screenfull of errors).

What's the best way to do this? I see that `pub get` has a `--dry-run` option, but I don't know if it's safe to use. Eg.:

- Is it safe to run in any folder (might not be a dart project root, might be a Flutter or Fuchsia project)
- Can I rely on specific output (it doesn't look like it's designed to be machine parseable - would you consider a flag to make it?)
- Is it fast, or does it go over the network for things?

**Comment by zoechi** [comment]
I guess one thing is to check if the `.packages` and `pubspec.lock` files exists.
`pub serve` also does a check if dependencies in `pubspec.yaml` were modified after the last time `pub get` or `pub upgrade` were run, but I don't know how they do that exactly.
You could also check the source of the IntelliJ plugin, because they show a hint to update as well when dependencies in `pubspec.yaml` were updated. Just comparing file dates isn't enough, because requiring to run `pub get` every time for example transformer settings were modified is too cumbersome.

**Comment by DanTup** [comment]
Ideally I'd like to avoid adding my own logic for this (to avoid it not matching, or needing maintaining) =)

**Comment by DanTup** [comment]
For now we're chekcing if `.packages` is missing or older than `pubspec.yaml`. It's not foolproof but is apparently what IntelliJ does and you can disable it globally, per-workspace or per-folder if you have a project that works in a way that this doesn't work (eg. the SDK repo).

**Comment by sigurdm** [comment]
@DanTup 
Did we land on something useful here? Can this issue be closed?

**Comment by DanTup** [comment]
I don't think anything specific has been done here, but there's a similar issue at #1447 that's a bit more specific and has more recent discussion so I don't think we need both.
