### ISSUE TITLE
Allow Pub to be updated independently of the Dart SDK

### ISSUE THREAD

**Issue by mcmahonjohn** [dart-lang/pub#1716]
I think pub should be able to be updated separately from the Dart SDK.

As it stands now, I believe, pub is only updated with new versions of the SDK. While I don't think, this is a trivial proposal, this would allow fixes, features, etc to be pushed out sooner.

So my thinking is as follows:
* Keep pub as part of the SDK releases to make migration easier, if a newer and compatible version is out, then users can manually upgrade.
* Add a command to pub that allows users to check for changes to pub
* Another command (or option of the above) to install changes for pub
* Add pub to pub.dartlang.org, so that would be where users find new versions of pub and stays within the current framework.

**Comment by nex3** [comment]
This would entail a *lot* of work, and I don't think the benefits would be worth it. We'd have to introduce an entirely new set of HTTP APIs for representing and downloading pub versions, including indicating things like which SDK versions each pub version is compatible with. We'd have to add UI for interacting with this and for communicating to the user which pub version they're using. We'd need to create a whole new set of build and deployment infrastructure for releasing pub versions onto pub.dartlang.org separately from the SDK. All of this in exchange for slightly faster releases just doesn't seem worth it, especially when the SDK already cuts weekly dev releases.

**Comment by mcmahonjohn** [comment]
Thanks @nex3 I was sure this would require a lot of change.

> We'd have to introduce an entirely new set of HTTP APIs for representing and downloading pub versions, including indicating things like which SDK versions each pub version is compatible with.
Don't pubspec.yaml files inform the user as well as the backend what SDK a package is compatible with?

Given that I had more time to think, the second and third options would not have to be implemented since it would be duplicative of pub to have a custom command to update. (ie: "Add a command to pub that allows users to check for changes to pub" and "Another command (or option of the above) to install changes for pub"). When pub would already provide this via the `pub global activate <package>` or `pub upgrade <package>`

> We'd have to add UI for interacting with this and for communication to the user which pub version they are using.

What do you mean by UI, print outs to the terminal? Or updating the website documentation?  If no new commands are added as I mentioned just above, then I think only the website documentation would be updated.

> We'd need to create a whole new set of build and deployment infrastructure for releasing pub versions onto pub.dartlang.org separately from the SDK

Yeah. The workflow would have to allow for more continuous releases/deployment than releasing with new SDK versions.

The Dart team takes a lot of lessons learned from NodeJS and NPM. NPM is packaged with each release of NodeJS, but users can update NPM independently. So if a new NodeJS version has an older NPM bundled, that wouldn't override the installed version.

At some point, I truly, believe the Dart team will have to cross that bridge. Is it not possible to retain this for consideration in future planning sessions?

> All of this in exchange for slightly faster releases just doesn't seem worth it, especially when the SDK already cuts weekly dev releases.

Dev releases are not the same as non-dev stable releases. Most people are not going to pull down the dev release even if it may be seen as stable within Google.

As stated above, a lot of languages/frameworks wind up separating their package manager from the core. It frees up the team to release more often and not "hold back" on changes. And simply, it's a common paradigm to remove unnecessary dependencies that prevent releases.

**Comment by Stargator** [comment]
Wow, just came here to say the same thing.

@nex3 I loved [your article on medium](https://medium.com/@nex3/pubgrub-2fb6470504f)

> All of this in exchange for slightly faster releases just doesn't seem worth it, especially when the SDK already cuts weekly dev releases.

So given the improvements that PubGrub brings, I think it would be beneficial for pub to separated from the SDK.

It's not just about small improvements, but would include major changes like the implementation of PubGrub within the package manager.

Sure the work would require pub to be treated like any other pub package plus handling checking the SDK installed works for the given pub package, but from my point of view pub has been a distinct feature of Dart.

A lot of other languages with package managers do bundle it with the SDK when releasing, but the managers can still be updated separately using stable versions of the SDK without depending on dev versions that can be brittle given whatever changes are being tested or worked on.

For example, my team has an outstanding ticket to migrate to Dart 2 and Angular 5 since January. Though it was only recently that we were able to build our angular app with the dev 43. That's months without able to build our application, but "hey we have the latest version of pub". That's not a valid use case for new releases of pub if the developers can't even run their application using a dev SDK version.

Aside from the Dart 2.0 changes, bundling improvements to pub within a dev version just prevents people are not working with the bleeding edge of Dart SDK and packages from using it.

I know this thread has already been discussed, but the separation doesn't have to be now, obviously, but I think it's in the best interest of the community whether this year or next.

Releasing newer versions of pub to the broadest set of the community (ie: not with a dev version of the SDK) would allow more people to see the changes and improvements and you would get feedback form non-Google engineers sooner than months down the line when a SDK is released.
