### ISSUE TITLE
Support environment: ^2.0.0

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1734]
I know the reason before was for backwards compatibility, but it seems like it is worth doing now.

**Comment by nex3** [comment]
Everything else in the pubspec we can change if we're willing to pay the migration cost, but the SDK constraint is inviolable. The reason is that we won't just break people with old code, we'll break people with old *SDKs*. Users need to be confident that their code will continue to work indefinitely if they don't upgrade their Dart SDKs, but if we let people upload packages with `environment: {sdk: ^2.0.0}`, old pub versions will try to process those packages and, I believe, crash. It's an unfortunate situation, but I think it's very important to preserve confidence that old Dart installs will continue to work.
