### ISSUE TITLE
feature: 'pub deps' should differentiate between compile- and test(dev)-dependencies

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/pub#1765]

**Comment by nex3** [comment]
You can see only the non-dev dependencies by passing the `--no-dev` flag.

**Comment by MikeMitterer** [comment]
Thanks! But maybe as a new feature: If you rewrite pub deps you can separate those trees by default, like it is in Gradle. I'm sure the flag you mentioned is somewhere documented but I couldn't find it. It's also not logical to me to mix those two things..

**Comment by nex3** [comment]
They're separated in the `compact` and `list` styles. It doesn't make as much sense to separate them in the `tree` style, because it includes transitive dependencies in the main tree and those may (transitively) depend on dependencies that are also listed in `dev_dependencies`.

> I'm sure the flag you mentioned is somewhere documented but I couldn't find it.

All command-line flags are documented in the `--help` output.
