### ISSUE TITLE
Pub get fails on appveyor but succeeds everywhere else

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/pub#1780]
[example failure](https://ci.appveyor.com/project/kevmoo/build/build/1.0.477)

I tested on my home windows machine with the latest dev release and that worked fine, it also works fine on my linux box.

The steps to test are to checkout out the [build repo](https://github.com/dart-lang/build), cd into the `e2e_example` dir, and run `pub get`. I only see this failing on appveyor, and it worked as of a couple hours ago, [see here](https://ci.appveyor.com/project/kevmoo/build/build/1.0.476).

I have a feeling this might just start working again in a bit and I will continue trying.

**Comment by nex3** [comment]
Can you run this with `--verbose` and include the output here?

**Comment by jakemac53** [comment]
https://ci.appveyor.com/project/kevmoo/build/build/1.0.484

**Comment by nex3** [comment]
I'm not sure what would be causing this... it looks like pub is just ignoring `convert` 2.0.1. It's *conceivable* that some package has a `<2.0.1` dependency on `convert`, but that would be *very* strange and I'd expect pub to report it in the output. There are no differences in the pubspec, either.

Only tangentially related, but why does `build_runner` have its lower bound for `convert` set to 2.0.1 rather than 2.0.0 in the first place? Dependency bounds should be as wide as possible, which means they should only ever be at major or minor versions since patch revisions don't introduce new APIs.

**Comment by jakemac53** [comment]
Ya it looks like we should have a wider constraint today, I can try changing that and it might solve this particular problem.

**Comment by lexaknyazev** [comment]
Seems to be similar to https://github.com/dart-lang/sdk/issues/31926. `convert` v2.0.1 [defines](https://github.com/dart-lang/convert/blob/2.0.1/pubspec.yaml#L8) prerelease min SDK constraint.
