### ISSUE TITLE
Support SemVer github repo's in Dart 2.0?

### ISSUE THREAD

**Issue by markcampanelli-wf** [dart-lang/pub#1805]
It would be so nice if Dart 2.0 could address using github repo's with SemVer ranges in pubspec.yaml's.

See https://github.com/dart-lang/pub/issues/1626 and https://github.com/dart-lang/pub/issues/1250 with https://github.com/dart-lang/pub/pull/1335.

I think the main blocker to https://github.com/dart-lang/pub/pull/1335 was a non-backwards compatibility, but the 2.0 breaking change could alleviate that.

cc @matanlurey

**Comment by nex3** [comment]
Pub's constraints on backwards-compatibility are much stricter than the language, since it has to work correctly with all existing pubspecs into perpetuity. There's also a human cost to backwards-incompatibilities, where we have to make sure everyone knows that a change is happening, why it's happening, and how to work around it. I don't think this feature is valuable enough to be worth that kind of migration pain even if we could make it work technically.

**Comment by natebosch** [comment]
> it has to work correctly with all existing pubspecs into perpetuity

With Dart 2 are we going to break compatibility (in resolving, not parsing) with all currently published packages?

**Comment by nex3** [comment]
Kind of. We're intentionally blurring the lines between packages that support Dart 2 and those that don't. Right now, we effectively treat all existing packages as supporting Dart 2, but no packages explicitly declare support for it. At some point, we'll need to start releasing versions of package that do explicitly support Dart 2, during which process pub will probably still support Dart 1 packages. Then once we have enough packages that accurately and explicitly state their Dart 2 support, we'll stop fudging older pubspecs and only support those that explicitly declare Dart 2. There's not really any point in there where it makes sense to make a sudden breaking change in how existing dependencies are declared.
