### ISSUE TITLE
Could not find a file named "pubspec.yaml" in

### ISSUE THREAD

**Issue by sinadarvi** [dart-lang/pub#1850]
i've got error like this when trying to install flutter.
i run 
`flutter doctor`
and suddenly i got error like this :
```
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error --no-packages-dir

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```

i've got the log, and here it is:
```
Could not find a file named "pubspec.yaml" in "/home/sina".
---- Log transcript ----
FINE: Pub 1.24.3
ERR : Could not find a file named "pubspec.yaml" in "/home/sina".
FINE: Exception type: FileException
FINE: package:pub/src/pubspec.dart 419                                    new Pubspec.load
    | package:pub/src/package.dart 138                                    new Package.load
    | package:pub/src/entrypoint.dart 146                                 new Entrypoint
    | package:pub/src/command.dart 42                                     PubCommand.entrypoint
    | package:pub/src/command/upgrade.dart 41                             UpgradeCommand.run
    | package:args/command_runner.dart 194                                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                             PubCommandRunner.runCommand.<fn>
    | dart:async                                                          new Future.sync
    | package:pub/src/utils.dart 102                                      captureErrors.<fn>
    | package:stack_trace                                                 Chain.capture
    | package:pub/src/utils.dart 117                                      captureErrors
    | package:pub/src/command_runner.dart 168                             PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 117                             PubCommandRunner.run
    | /tmp/tmpj91Zcx/dart-1.24.3/dart/third_party/pkg/pub/bin/pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                                          _Completer.completeError
    | package:pub/src/command/upgrade.dart 51                             UpgradeCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                                          new Future.microtask
    | package:pub/src/command/upgrade.dart 40                             UpgradeCommand.run
    | package:args/command_runner.dart 194                                CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                          new Future.microtask
    | package:args/command_runner.dart 142                                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                             PubCommandRunner.runCommand.<fn>
    | dart:async                                                          new Future.sync
    | package:pub/src/utils.dart 102                                      captureErrors.<fn>
    | package:stack_trace                                                 Chain.capture
    | package:pub/src/utils.dart 117                                      captureErrors
    | package:pub/src/command_runner.dart 168                             PubCommandRunner.runCommand
---- End log transcript ----
```

----------------------
OS : Ubuntu 17.10

**Comment by zoechi** [comment]
Sounds like a network issue
You don't have by any chance a space in the Flutter install directory path?

**Comment by sinadarvi** [comment]
@zoechi even deleting pub cache wasn't helpful. any idea ?

**Comment by zoechi** [comment]
I wouldn't expect deleting pub cach to have effect

**Comment by nex3** [comment]
This issue was moved to flutter/flutter#15948

**Comment by zoechi** [comment]
@nex3 can this issue be reopened here? It looks like this error is caused by invalid `pubspec.yaml` and there should be a better error message from pub.

I saw an example where the first line had a few spaces before `name: ...` and flutter/flutter#15948 mentions examples with invalid `path: ...`

**Comment by natebosch** [comment]
cc @mit-mit to triage

**Comment by zoechi** [comment]
There are actually 2 different cases (which I wasn't aware before)
```
Could not find a file named "pubspec.yaml"
```

A few I found in a Google search. Some are older but I think they show that in many situations the error message is not helpful. Perhaps there is a way to get more information about the root cause.

- https://github.com/dart-lang/build/issues/1469
- https://github.com/flutter/flutter/issues/22175
- https://github.com/fluttercommunity/flutter_launcher_icons/issues/50
- https://github.com/flutter/flutter/issues/16100
- https://stackoverflow.com/questions/27217278/could-not-find-a-file-named-pubspec-yaml-in
- https://stackoverflow.com/questions/52202923/flutter-running-flutter-fails-could-not-find-a-file-named-pubspec-yaml-upd?rq=1
- https://stackoverflow.com/questions/51317203/could-not-find-a-file-named-pubspec-yaml-in-users-username
- https://stackoverflow.com/questions/42209519/could-not-find-a-file-named-pubspec-yaml-in-home-vagrant-pub-cache-hosted-p
- https://intellij-support.jetbrains.com/hc/en-us/community/posts/207306545-Dart-Could-not-find-a-file-named-pubspec-yaml-

and there is a similar error message
```
Error: No pubspec.yaml file found.
```
- https://github.com/flutter/flutter/issues/21305
- https://github.com/flutter/flutter/issues/27911
- https://github.com/flutter/flutter/issues/17650
- https://github.com/flutter/flutter/issues/17472

which looks like it comes from Flutter https://github.com/flutter/flutter/search?q=%22No+pubspec.yaml+file+found%22&unscoped_q=%22No+pubspec.yaml+file+found%22

I just put this here to gather more information and perhaps find a pattern.

**Comment by mit-mit** [comment]
@zoechi did you come across a simple repro for this?

**Comment by zoechi** [comment]
@mit-mit no, every attempt to reproduce failed so far. 

There were 2 cases where fixing the content of `pubspec.yaml` seems to have solved it, but I wasn't able to reproduce that way.

Most other cases were broken `~/.pub-cache` or where some radical actions like reinstalling Flutter seems to have fixed it.

**Comment by AshrafulalamRasel** [comment]
Simple write in terminal ,
cd your project name  // for windows
flutter run // use for run your application .

**Comment by shinayser** [comment]
I am having this problem right now. I've already tried deleting the whole `flutter `directory but nothing works.

Any idea what may be causing this?

**Comment by Dhciolfi** [comment]
I am having the same problem.

Could not find a file named "pubspec.yaml" in "C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-0.13.0".

pub get failed (66)

**Comment by iftee939** [comment]
I'm having an error Could not find a file named "pubspec.yaml" in "C:\Users\iftek\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\quiver-2.0.1".

**Comment by mockturtl** [comment]
I had changed some `git:` dependencies to `path:` dependencies.

```diff
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -18,19 +18,13 @@ dependencies:
   foo:
-    git:
-      url: git@github.com:myorg/foo.git
-      ref: mine
+    path: /Users/me/proj/flutter/foo
``` 

After reverting, I get the error.

```diff
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -18,13 +18,19 @@ dependencies:
   foo:
-    path: /Users/me/proj/flutter/foo
+    git:
+      url: git@github.com:myorg/foo.git
+      ref: mine
```

```sh
$ flutter packages get
Could not find a file named "pubspec.yaml" in git@github.com:myorg/foo.git 6d8373ad034368c7247dc9c8c9ae324f5aa6afa3.
```

If I remove the `.git` suffix from the url, `flutter packages get` runs normally.

```diff
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -19,17 +19,17 @@ dependencies:
   foo:
     git:
-      url: git@github.com:myorg/foo.git
+      url: git@github.com:myorg/foo
```

**Comment by phattranky** [comment]
Remove ```.git``` work for me.

**Comment by mit-mit** [comment]
This is a pretty old, closed bug. If anyone is still experiencing issues, please file new issues (and kindly include as much information, repro steps, etc. as possible).

**Comment by galyathee** [comment]
I reproduced it simply.
I create a basic flutter application, I then copy the following

path_provider: ^1.5.1
  just_audio: ^0.0.6
  flutter_tts: ^0.8.5
  rxdart: ^0.23.1
  audio_service:
    path: ../

directly from the page : https://github.com/ryanheise/audio_service/blob/master/example/pubspec.yaml 

Because just_audio, flutter_tts, etc... have suddenly a TAB more in front of them I remove the tabs manually to appear aligned:

path_provider: ^1.5.1
just_audio: ^0.0.6
flutter_tts: ^0.8.5
rxdart: ^0.23.1
audio_service:
  path: ../

packages get gives then:
/_Users/christianfontan/dev/flutter/bin/flutter --no-color packages get
Running "flutter pub get" in singing_buttons...                 
Could not find a file named "pubspec.yaml" in "/Users/christianfontan/AndroidStudioProjects".
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/christianfontan/AndroidStudioProjects".)
Process finished with exit code 66_

Obvious reason: bad chars in the yaml file :) If I write the same content manually the issue disappears

**Comment by jonasfj** [comment]
> I create a basic flutter application, I then copy the following
```
audio_service:
   path: ../
```

That's always wrong.. unless you're doing it from the `audio_service/example` folder, you can't path import..

**Comment by galyathee** [comment]
Hi, can really be, but tgere was a question about how to reproduce...

**Comment by mfrischbutter** [comment]
Instead of
```
audio_service:
   path: ../
```
remove the "path:" and just use
`audio_service:`
or the given version that you need.

**Comment by safalstha142** [comment]
**I got the solution** 
1. First go to the  \flutter\.pub-cache\hosted\pub.dartlang.org 
2. Delete all the package 
3. Then Congrats your problem solved 

The problem is due to the pubspec.yaml file missed in your package or plugins
This step work for me
