### ISSUE TITLE
Remove the package file physically when I remove it from dependency

### ISSUE THREAD

**Issue by jianggaocheng** [dart-lang/pub#1959]
I was a node.js programmer before, in node.js, the dependency are divided into two types, 「global dependency」and「project dependency」，the 「global dependency」 are placed in a global path and can be shared by every project, the 「project dependency」are placed in the project directory.

It means for some packages I only used in one project, I can put it to 「project dependency」, and when I do not need it, I can just delete it physically by cmd 「yarn remove」.

In dart, all dependency are public and can be shared by every project, The problem is maybe sometimes I just want to 「try」some packages, and I want to remove it physically from my PC after my trial

I think that we need a way to remove dependency physically otherwise It will take more and more space to store the dependency.

**Comment by jianggaocheng** [comment]
[How to remove a dev_dependencies physically, which is as 「yarn remove」in nodejs](https://github.com/flutter/flutter/issues/20071)

**Comment by jakemac53** [comment]
The problem is that pub stores all dependencies in a shared cache, which is in on the surface a good idea and uses less disk space. However, over time this actually becomes significantly worse for disk space usage since it doesn't store any information about what projects are depending on what versions of packages, and thus it can't ever delete a version of a package that was downloaded.

In addition to causing it to use increasingly more disk space over time, it also has the unfortunate side effect of making `pub cache repair` take more and more time.

The only existing solution I am aware of is to manually delete your pub cache directory periodically, but then you will have to pub get all your packages again. You can find that by looking at your `.packages` file, it should be pretty apparent from the paths in there where it is located.

Longer term though I agree that some way of actually cleaning up unused dependencies would be great.

**Comment by jamesderlin** [comment]
> However, over time this actually becomes significantly worse for disk space usage since it doesn't store any information about what projects are depending on what versions of packages, and thus it can't ever delete a version of a package that was downloaded.

Can we make `pub` start keeping such information?

Even without that, I think we should have *some* mechanism for managing the size of `.pub-cache`.  Here are some ideas:

* Add a `clean` command that does the equivalent of blowing away `~/.pub-cache/hosted/` so that users don't have to figure it out on their own. (One issue is that doing this breaks things like Flutter DevTools, and users will need to re-run `pub global activate devtools`.  Would be nice if we could somehow be smarter about not breaking that.)
* Add a command or option to delete all but the latest version of each cached package. (If the latest version is a `-dev` version, possibly latest stable and latest dev versions.)
* Check access times and remove least-recently-used packages.  This could be combined with a maximum cache size so that we don't need to figure out an exact age cut-off.

I don't think we necessarily need a perfect mechanism; at worst people will need to re-run `pub get`. If we really want, before pruning the cache, we could print messages about needing to re-run `pub get` and possibly prompt.

**Comment by sigurdm** [comment]
> Add a clean command that does the equivalent of blowing away ~/.pub-cache/hosted/ so that users don't have to figure it out on their own. (One issue is that doing this breaks things like Flutter DevTools, and users will need to re-run pub global activate devtools. Would be nice if we could somehow be smarter about not breaking that.)

We now have a [`dart pub cache clean`](https://dart.dev/tools/pub/cmd/pub-cache#clearing-the-global-system-cache) command that empties the cache.

That can be followed up by a `pub get` in each package. That gives a full garbage collection of the cache (but at the cost of re-downloading all active package-versions).

I don't think we plan to do much more here in the close future.

Please complain if you think doing something smarter here is needed, and I can reopen.
