### ISSUE TITLE
Starting a `pub.bat` process with `detachedWithStdio` spawns a new shell in Windows and does not forward IO.

### ISSUE THREAD

**Issue by grouma** [dart-lang/pub#2042]
This is likely related to https://github.com/dart-lang/sdk/issues/35809. Note that calling the pub snapshot directly does not have this issue.

**Comment by natebosch** [comment]
I think this is probably a general `.bat` thing - do we think there is anything that we can do within pub itself to change this?

**Comment by grouma** [comment]
`dart.bat` does not have this issue. I believe it's because of the snapshot logic. We run a nested process with standard process mode. See here: https://github.com/dart-lang/pub/blob/90079421675e67c172f78081db37fc0cca64789f/lib/src/dart.dart#L55

**Comment by DanTup** [comment]
> `dart.bat` does not have this issue

Isn't Dart an `exe`? `exe`s can be executed irectly, but `bat`s are interpreted by the shell so must be launched through one. Dart Code has had all sorts of issues with pub/flutter as a result of this (for ex. the pid/process handle you get are for the shell, and might not pass kill signals on to the spawned process).

FWIW, in the nodejs docs (which I'm familiar with only because Dart Code has many issues because of pub and flutter being `bat`s :)) it calls out some of this behaviour on Windows:

> On Windows, setting `options.detached` to `true` makes it possible for the child process to continue running after the parent exits. The child will have its own console window. Once enabled for a child process, it cannot be disabled.

So there may be some OS limitations here. I'm not sure about stdio though (in Dart Code we never spawn anything detached).

**Comment by sigurdm** [comment]
Pub.bat no longer exists (it is not `dart pub`).

Closing as obsolete.
