### ISSUE TITLE
Suggest running pub upgrade if the SDK version has changed

### ISSUE THREAD

**Issue by munificent** [dart-lang/pub#2168]
We increasingly ship "breaking changes" as minor version bumps in the Dart SDK. We do this because bumping the major version of the SDK is a very large, destabilizing change and these "breaking" changes usually only break a very very small amount of code.

At the same time, they *can* break things and when that happens, it's frustrating for users. Typically, we mitigate that by fixing packages that get broken. But a user *depending* on one of those packages won't get that fix until they upgrade. The version solver doesn't help because the older version of that package thinks it *does* work with the latest SDK, so a `pub get` does not force it to upgrade.

Here's a simple tool change we could do to alleviate this: 

1. Store the current concrete Dart SDK version number in the lockfile when it gets generated. (I thought we did this already, but I don't see it in there.)

2. When the user runs `pub get` if the current Dart SDK version is at least one minor version later than the version in the lockfile, print out a suggestion that they may want to run `pub upgrade` if something doesn't work.

3. (Bonus): When printing the suggestion, include the text of any breaking changes in the SDKs they have upgraded to since the last time they ran `pub get`. This would require us to store that in some canonical, parseable form. Pub could probably yank it from the CHANGELOG file itself with some reasonable amount of success.

What do you think?

@lrhn

**Comment by lrhn** [comment]
Breaking changes in minor version increments are bad, but unavoidable if we want to be able to change things at all&mdash;since basically all changes in Dart are technically breaking. Incrementing the major version number is a major impact on the ecosystem, so we reserve that for big unmitigable breaking changes

This is a simple and safe approach for recommending a `pub upgrade`.
It avoids maintaining metadata on the side to guide upgrading (a release with no breaking changes, which should still happen, would not require any action).

My guess is that when we get language versioning, people are going to be more interested in updating their SDK constraints anyway, which may drive some more upgrades.

**Comment by sigurdm** [comment]
We are now always suggesting upgrade (via `outdated`) if there are newer versions available.

I think that is enough
