### ISSUE TITLE
Pub publish - Corporate authentication fails on ChromeOS (Pixelbook)

### ISSUE THREAD

**Issue by mk13** [dart-lang/pub#2187]
# Environment

- `pub version` or `flutter pub version`: 2.4.0
- OS version: ChromeOS Version 75.0.3770.144 (Official Build) (64-bit)
- Are you using the Chinese community mirror or a corporate firewall? On Google corporate network

# Problem

First time trying to `pub publish` pageloader on a new Pixelbook. As expected, an authentication prompt opens and I click the link.

I see a Google login screen where I click my corporate email (linked to my account).

Afterwards, I'm redirected to a local host page, ex: `http://localhost:XXXXX/?code=....`. Page responds with: "This site can’t be reached localhost refused to connect."

I was able to bypass this and publish by using my workstation directly, so this isn't a blocker.

I've tried this on my home network while on corporate VPN. I've also tried this using the work WiFi. Same issue both times.

**Comment by jonasfj** [comment]
I think the problem is that the `pub` CLI client is listening on `localhost`, but if you're on a chromebook you're probably running `pub` in  a virtual machine or container, right?

A workaround is to type `curl http://localhost:XXXXX/?code=.....` into the terminal while `pub publish` is running (after the browser tells you it can't connect to localhost).

What development setup are you using? Is there any documentation for how to listen on localhost host? Can we detect the environment?

**Comment by mk13** [comment]
Looks like the `curl ...` works, thanks! That makes sense, I think there's three possible solutions here:

1. Using `curl` as in your suggestion.
2. Changing `localhost` to the the hostname of crostini (ex: `"penguin.termina.localhost:XXXXX"`) would have also worked.
3. Use SSH tunneling, which seems to be overkill.

I'm just using the default corporate set up and haven't done anything special; basically out-of-box set up. I'm not sure `pub` is able to detect the environment, but I think if it can - changing `localhost` to that of the default terminal hostname would work.

**Comment by jonasfj** [comment]
I filed https://github.com/dart-lang/site-www/issues/1822 suggesting that we add this to:
https://dart.dev/tools/pub/troubleshoot
