### ISSUE TITLE
pub publish doesn't follow file symlinks

### ISSUE THREAD

**Issue by werediver** [dart-lang/pub#2193]
# Environment

- `pub version` or `flutter pub version`: Pub 2.4.0
- OS version: macOS 10.14.6
- Are you using the Chinese community mirror or a corporate firewall? No.

# Problem

`pub publish` ignores file symlinks (but follows directory symlinks).

For example, in a multi-package repo I want the top level README.md to be symlinked from some of the packages (../README.md):

https://github.com/werediver/sum_types.dart/tree/5657f9d83f26cebac98ab3a0d8d5ff7e060d0859/sum_types_generator

## Expected behavior

I expect pub to resolve file symlinks and include the target files in the package as if they were in place of the symlinks.

## Actual behavior

Pub entirely ignores file symlinks during publishing as if they do not exist.

## --trace output

Not relevant (no errors).

**Comment by werediver** [comment]
No, it does. I ended up with broken symlinks, which were legitimately ignored by pub.

**Comment by frencojobs** [comment]
How did you manage to solve this? I'm also having an error where the linked files and folders outside of the project base are recognized as broken symlinks.

**Comment by werediver** [comment]
@frencojobs I didn't use sym-links pointing outside the package directory, so it was never a problem for me. It is likely that such links are not accepted by pub for security and/or package integrity reasons.

You may consider using hard-links, if you think you have such a need.

**Comment by frencojobs** [comment]
Thanks. Even though I can't get in contact with the author of the [Retrofit](https://github.com/trevorwang/retrofit.dart) library, it seems like the library is structured a lot like what I needed, monorepo with symlinks. So, I actually think it's possible but maybe I'm doing something wrong.

I'm currently using hard-links because I'm in a hassle right now. But it doesn't look like the best idea.
