### ISSUE TITLE
Support authentication/API tokens

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#2201]
I'm working on automating the publishing workflow of my package using CI, and while it's feasible now, it could be easier and more secure. Pub currently needs a full `credentials.json` file to authenticate with the server, and it needs it to exist in `~/.pub-cache/credentials.json`. This makes storing the credentials and passing them to the pub client difficult in comparison to other package managers.

I'd like to see the ability to create short authentication tokens that can be stored ([encrypted](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)) in CI configuration and passed to pub as an environment variable (`PUB_TOKEN`?). This is how [GitHub does authentication](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line), for example.

This would also benefit security, because individual tokens can easily be revoked if they happen to leak (as in https://github.com/dart-lang/pub/issues/2132).

**Comment by jonasfj** [comment]
We're looking at adding support authentication using tokens in https://github.com/dart-lang/pub/issues/1381, but this mainly aimed at third-party servers.

My thinking for `pub.dev` is that we leverage service-accounts, these can already interact with `pub.dev`, but since they can't receive emails you can't invite a service account to join your package.
The solution is probably to build an API for accepting an invitation... But this haven't been properly explored yet -- it might be more attractive to publish tags from github instead with direct github integration serverside.

All of this is in the brainstorming phrase, we have no plans to work on this anytime soon.

**Comment by nex3** [comment]
How exactly would service accounts address this? I already have an account I use to automate all my release infrastructure (sass.bot.beep.boop@gmail.com)—I don't want to have to add another one just for pub.

**Comment by jonasfj** [comment]
One could imagine a login subcommand that accepts exported service account keys.

In general gmail accounts are a poor choice for bots...

But, yes, we have no fully conceived solution yet or plans to make one.

**Comment by sigurdm** [comment]
We now have this! `dart pub token add`.
