### ISSUE TITLE
Feature: pub publish --tag-release

### ISSUE THREAD

**Issue by mklim** [dart-lang/pub#2250]
Thought of this while I was writing https://github.com/flutter/flutter/issues/42934#issuecomment-551931407.

It's now desirable for plugins to have their repos to be tagged with the semantic version of their pub releases. For example when package `foo` publishes commit `abcdef` as `1.0.0` on pub, that commit should also be tagged as `v1.0.0` in its main repo as listed on pub. 

I am considering writing a wrapper around `pub publish` myself to do this, since manually remembering to do this is going to be painful. But pub itself may be a better fit for this since it already has pretty much all the information it needs already.

Potential complications:
- Does it make sense to make this git only?
- The tagging format needs to be different for monorepos. I'm not sure if the pub tool is totally aware of whether it's in a monorepo or not.
- Publishing and pushing tags are independent. What should pub do if it publishes the package to pub but fails to push the tag? I'm thinking exit with a nonzero status code and print out exactly what happened with a suggested git command for the user to try themselves, but I can see it being surprising that the package could be published at all and not tagged too. 
- Pub knows the repository's bare URL but it doesn't know if it's a remote or what it's named in the current local checkout. Not sure exactly how to push tags given that.

I can ramp up on pub and try to implement this myself if it makes sense for it to live here.

/cc @jonasfj @csells

**Comment by jonasfj** [comment]
I think this is something we should consider. I've been contemplating if it might not be better to offer automated publishing as a side-effect of tagging in `git`. So that packages are published git `git tag v1.2.3 && git push origin v1.2.3`.

This could work by publishing from Cloud-Build without many changes to pub client or pub server.

side note:
 * The `dartlang` org seem to have a convention for tagging with `1.2.3` and not prefixing `v`.
   (I don't know if any cases where this is problematic, but I can only imagine there is some).
 * Tagging for `mono_repo`'s should be solved.
 * Making `pub` more git aware seems very reasonable, detect dirty files, etc.
  (@sigurdm and I have long been dreaming about detecting dirty files).

Note. publishing from automation by pushing a git tag does not invalidate the usefulness of `pub publish --tag-release`. But it does make publishing this way less attractive.

**Comment by sigurdm** [comment]
I think now that we are launching automated publishing (should be ready any day now) from github I'll close this.

That will be our recommended workflow - pushing a tag is what publishes the given version.

**Comment by sigurdm** [comment]
The documentation of automated publishing is here: https://dart.dev/tools/pub/automated-publishing
