### ISSUE TITLE
Dependency on platform-specific libraries is not surfaced in pubspec.yaml

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#2278]
When a package add an import of `dart:io` or `dart:js` it reduces the number of places where the package works. As a result such an import might be a breaking change.

However, this is not surfaced in the `pubspec.yaml`. So a user running `pub` in a web project can't avoid upgrading to a new incompatible version, because `pub` is unaware of this incompatibility.

There are also no lints or warnings to make this evident the user developing a new minor version of an existing package.

-----
It's not clear how to solve this, whether annotating `dart.library.io: true` in `pubspec.yaml` or annotating platform/runtime limitations, when this apply.

**Comment by jakemac53** [comment]
One option here is to take inspiration from the internal bazel rules here, which already do have this understanding.

Initially, it worked by specifying which _platforms_ they supported (web, flutter, vm). However this turned out to not scale well - whenever a new platform is added then that causes a huge amount of churn.

To fix that we changed things to specify which `dart:` libraries they use (at least for the platform specific ones). Then each platform knows which of those libraries it chooses to support, and you can derive platform support for each package from that.

In general I think the library based support is better, but requiring users to list every single `dart:` library they use in their pubspec would also be somewhat burdensome, especially for things like `dart:convert`, `dart:collection`, etc, which aren't today platform specific at all.

**Comment by sigurdm** [comment]
How do handle packages that have several entry-point libraries, eg. one for web and one for the vm? For example `package:http/http.dart` with `package:http/io_client.dart` `package:http/browser_client.dart?
In google3 we specify dependencies per dart_library, but here we are restricted to do it per package (unless we expand significantly on the current design)

**Comment by jakemac53** [comment]
Hmm true, that makes it more difficult for external packages. I am not sure what the right approach here would be then.

**Comment by jakemac53** [comment]
I suppose this would require something like the old package "features" proposal, but with additional functionality to say which entrypoints are included in each "feature", and which libraries are required for each.

**Comment by sigurdm** [comment]
I think that if a new package-version adds a dependency to `dart:io` it is no different from other breaking changes. I don't think the solver needs to know about it.

If you get broken by an upgrade, you will get diagnostics from the compiler/analyzer telling you that you were broken.

I think it is more mysterious if you cannot upgrade to the new version you can see on pub.dev because it requires something new.

Tentatively closing as wontfix
