### ISSUE TITLE
pubspec.yaml parser ignores invalid keys.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#2311]
When parsing the pubspec.yaml invalid keys are ignored.

I recently had a problem with my dependency_overrides not working.

I eventually worked out that the problem was that I had missed spelt dependency_overrides as dependency_overides (not the missing 'r').

Errors like invalid key names should be spat out by the parser.
I can't be the first person who has spent some time trying to work out what's wrong with my pubspec.yaml.

**Comment by jakemac53** [comment]
For better or worse this is an intentional decision, it allows other tools to piggyback off of the file and add their own configuration. Also any key which has ever been supported has to be supported in perpetuity.

We could probably try to catch common misspellings though and at least warn. Dependency_overrides in particular is easy to typo.

Maybe if an unknown key is within an edit distance of 1 or 2 from a know key give a warning that it is likely a misspelling?

**Comment by sigurdm** [comment]
> We could probably try to catch common misspellings though and at least warn. Dependency_overrides in particular is easy to typo.

+1 I think we should do this. I hate spelling dependency_overrides myself.

**Comment by bsutton** [comment]
> Also any key which has ever been supported has to be supported in perpetuity.
An approach similar to deprecation could be used to overcome that problem.

If you want to allow other apps to add their data why not force some conventions on them:

e.g.
All third party data must appear under a special section such as:
```
custom:
  my_custom_data:
```

Under the custom section each app could be responsible for its own section and the validation thereof.
pub could then fully validate the rest of the file.

The edit distance would be helpful but enforcement would be much better.

**Comment by jakemac53** [comment]
It is probably worth analyzing all published packages to see how many of them violate the desired rules (no unrecognized keys) today, and in what ways (intentional, or likely spelling mistakes, etc).

It should be noted that extensibility is not the only reason that it is so permissive. For instance the format actually has to not just be backwards compatible but also forwards compatible (any version of pub has to be able to parse all previous and future pubspecs). As an example this is why the sdk version ranges don't allow ^ syntax to this day. Mostly this is during the version solve I believe, but it could quite possible have a more lax implementation in that scenario, and only enable warnings/errors for the root package or something like that.

cc @munificent do you remember if there are other concrete reasons that unrecognized keys are allowed?

**Comment by sigurdm** [comment]
@jonasfj suggests we could consider implementing a lint for the analyzer that warns about keys not recognized by current pub.

Then custom data can be added with a `# ignore:...` comment.

**Comment by jakemac53** [comment]
I think some sort of edit distance checker in pub would be more useful tbh - the analyzer isn't used by everybody. It would definitely help some people though.

It would also need to be enabled by default to be very useful, so probably not a lint per say but a hint.

**Comment by munificent** [comment]
> It is probably worth analyzing all published packages to see how many of them violate the desired rules (no unrecognized keys) today, and in what ways (intentional, or likely spelling mistakes, etc).

Someone on the team did that a while back. I can't recall who but there were a decent number of extra keys. Some were clearly typos while some others did look like they were deliberate uses.

> cc @munificent do you remember if there are other concrete reasons that unrecognized keys are allowed?

It allows older versions of pub to consume pubspecs authored by people using newer versions. Any key that pub disallows becomes a key that no future version of pub itself can ever use either. Ignoring unrecognized keys enables pub to be forward compatible.

**Comment by bsutton** [comment]
> Ignoring unrecognized keys enables pub to be forward compatible.

Then lets lint them with an option to suppress the lint.

Failing silently is a really bad idea.
