### ISSUE TITLE
pub outdated --json is confusing with --no-dev-dependencies

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub#2552]
It shows all current packages, even though they are dev-dependencies

**Comment by jonasfj** [comment]
Okay, I think we're interpreting it wrong:

```js
    {
      "package": "yaml",
      "current": {
        "version": "2.2.1"
      },
      "upgradable": null,
      "resolvable": null,
      "latest": {
        "version": "2.2.1"
      }
    }
```

When `upgradable` is `null`, while `current` is not... then it must be because it was deselected. I'm not sure we should not include these. Maybe we should omit them since this is what the flag ask for... But at-least consumers can actually filter on this.
