### ISSUE TITLE
pub publish: issue warning if a package constraint is too restrictive

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#2575]
See https://github.com/leisim/dartx/issues/99

`dartx` was published with a constraint on `pkg:collection` of ` ">=1.14.11 <1.15.0"` which caused problems.

There are valid reasons to have such a tight constraint – usually if there are exports of members within the dependency.

**Comment by sigurdm** [comment]
Just to be entirely sure: you suggest warning about all constraints that are not using the '^' form?

**Comment by kevmoo** [comment]
> Just to be entirely sure: you suggest warning about all constraints that are not using the '^' form?

Not exactly

My rough thinking.

1) Only applies to constraints of the form `>=X <Y`
2) Where the constraint is more restrictive than `^X`

**Comment by sigurdm** [comment]
> Where the constraint is more restrictive than ^X

Why not standardizing on warning when not

**Comment by jonasfj** [comment]
I don't think we do this so long as [our recommendation][1] is that if `package:widgets` exports something from `package:collection`, then `package:widgets` should have tighter version constraints on `package:collection` (typically only allowing patch versions, not minor versions as would be allowed by `^` constraints). 

I'm not sure many people do this, but it's our recommendation and until that changes, we should not make a warning for this.

[1]: https://dart.dev/tools/pub/versioning#constraint-solving-for-exported-dependencies

**Comment by jonasfj** [comment]
> Personally, I'm not convinced tighter constraints is worth the hassle, but I do see that it makes sense if you are implementing and exporting an interface defined in another package.

On the other hand, if `package:widgets` is implementing an interface defined in `package:collection` then adding a `sortBackwards()` method in `package:collection` is a breaking change.

Unless the author of `package:collection` annotated the interface with `@sealed`, adding a method to an interface might reasonably be considered a breaking change.

But then again, the author of `package:widgets` might want to put a tighter constraint in, because they expect that `package:collection` won't consider adding a new method as a breaking change.

I suspect that why we have the recommendation. In any case, as long as the recommendation stands, we should not be warning users about tight constraints.
