### ISSUE TITLE
why deprecate authors and author in pubspec.yaml?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/pub#2751]
like title

**Comment by sigurdm** [comment]
We did this because we no longer show them on the pub.dev site.

They are not verified. We introduced https://dart.dev/tools/pub/verified-publishers to give some amount of trust in the publisher.

This is discussed more in: https://github.com/dart-lang/pub-dev/issues/3189 .

Closing this for now. Please reopen if there are further questions.
