### ISSUE TITLE
Regression in test execution behavior 

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/pub#2753]
Hi; with https://github.com/dart-lang/pub/commit/63b56ea42fc58dd7eafa83c5b3c0b05ffdef0712 we're seeing issues when executing tests. Specifically for IDEs, when debugging tests, test execution pauses at the end of the test run. This happens whether the tests succeed or fail.

This is a regression in the test execution user experience. Instead of trying to fix up existing debugger clients to work around this, I think we should revert https://github.com/dart-lang/pub/commit/63b56ea42fc58dd7eafa83c5b3c0b05ffdef0712, and / or find another way to do control flow other than throwing an exception.

See also https://github.com/flutter/flutter-intellij/issues/5043 and https://github.com/Dart-Code/Dart-Code/issues/2949.

cc @dantup @sigurdm @jonasfj

**Comment by jonasfj** [comment]
@sigurdm, @dantup, and I had a chat about this.. We found that it would probably be best to use:
`dart --pause_isolates_on_start=true --write-service-info=/tmp/foo.txt run test:test`

I can see the argument to try and find a workaround other than throwing an exception so that it doesn't break existing flows.

However, the underlying problem here is that existing IDE integrations are running a debugger on a process that includes `pub`, rather than running on test binaries directly. So they are naturally affected by internal changes in `pub`, we cannot make any stability guarantees here (ie. the behavior you experience if you attach a debugger to the `pub` process, may change at any time -- the set of exceptions we throw and catch is a private API).

I'm not sure we can just revert 63b56ea as the embedding of `pub` in `dartdev` now depends on this.. So it might be easier to fix it, rather than reverting all the changes made since that landed.

**Comment by jonasfj** [comment]
Drafted https://github.com/dart-lang/pub/pull/2755 let's see if it passes travis :D

**Comment by devoncarew** [comment]
Thanks for the speculative PR! 

> @sigurdm, @DanTup, and I had a chat about this.. We found that it would probably be best to use:
> `dart --pause_isolates_on_start=true --write-service-info=/tmp/foo.txt run test:test`

Gotcha, but note that my immediate concern is more with existing clients in the wild and not necessarily what to do in the future.

> However, the underlying problem here is that existing IDE integrations are running a debugger on a process that includes `pub`, rather than running on test binaries directly. So they are naturally affected by internal changes in `pub`, we cannot make any stability guarantees here (ie. the behavior you experience if you attach a debugger to the `pub` process, may change at any time -- the set of exceptions we throw and catch is a private API).

I'm certain there are improvements that can be made to how we execute tests. When we initially added the ability to debug tests, we weren't able to get good agreement with the then package:test maintainer about how it could be done, or even if it was an important use case. The current way we debug tests on top of `pub run test` is certainly something we can look into improving in the future.

**Comment by devoncarew** [comment]
In any case, irrespective of the results of the build status of the PR, I'm happy to meet to discuss this.

**Comment by jonasfj** [comment]
> I'm certain there are improvements that can be made to how we execute tests.

Maybe it would be best if test started it's own `dart` subprocesses, rather than using `Isolate.spawnUri` with data URIs..
At-least for debugging... That said, I think we'll have reduced the scope of the problem with `pub` embedding in `dartdev` as this now runs in an isolate that (afaik) doesn't show up in the debugger.

**Comment by devoncarew** [comment]
> rather than using Isolate.spawnUri with data URIs

I've heard from @mraleph that the use of data urls complicates diagnosing when things go wrong with tests. I suspect that there's room for simplifications w/ package:test arch. and how it executes tests. cc @grouma @natebosch

**Comment by natebosch** [comment]
> I suspect that there's room for simplifications w/ package:test arch. and how it executes tests.

We haven't found any room without some invasive breaking changes.

> Maybe it would be best if test started it's own `dart` subprocesses, rather than using `Isolate.spawnUri` with data URIs..
> At-least for debugging...

Wether we start a subprocess or an isolate is orthogonal to whether we use a file URI or a data URI. We cannot directly run user test code as it is written today, it must be wrapped in a surrounding library that we generate. Either we write this generated code to a file, or keep it as a data URI. Whichever we choose we can then run it in an isolate or a separate VM process (assuming the VM can take a data URI as a command line argument). Trying to write these to a file instead of keeping them as data URIs would likely incur more complexity than it solves.

**Comment by sigurdm** [comment]
@jonasfj do we need to roll+pick this into beta?

**Comment by jonasfj** [comment]
yeah, let's roll and send to cherry picking.

**Comment by sigurdm** [comment]
I think this was fixed by the cherry-pick back-when
