### ISSUE TITLE
dev_dependency_overrides or equivalent

### ISSUE THREAD

**Issue by Daegalus** [dart-lang/pub#2819]
I have had nothing but headache using this  while trying to prepare for nullsafety, and no I hit a hard blocker because of it.

My package `uuid` depends on `crypto` and has dev_dependencies for `test` and `pedantic`.

`crypto` has a nullsafety version which I depend on in my nullsafety version. I depend on the nullsafety `test` package, but it still depends on `web_socket_channel` which is not a nullsafety version, and depends on the non-nullsafety version of `crypto` causing dependency issues.

I have a dependency override for `crypto` to the nullsafety version so that everything works. But it overrides my main dependency on `crypto` causing `pub lish` to fail with an error message about overriding a non-dev dependency.

```
Package validation found the following error:
* Your pubspec.yaml must not override non-dev dependencies.
  This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.
```

Can we get a `dev_dependency_override` of some sort that only overrides dev-dependencies and ignores regular dependencies?

Link to my pubspec for reference: https://github.com/Daegalus/dart-uuid/blob/master/pubspec.yaml
Link to my ticket on the web_socket_channel repo: https://github.com/dart-lang/web_socket_channel/issues/138
Issue tracking all this in uuid repo: https://github.com/Daegalus/dart-uuid/issues/50

**Comment by sigurdm** [comment]
Hopefully we can get the web_socket_channel to upgrade it's dependency-range on package:crypto if they truly are compatible.

dependency_overrides in some sense are dev-only already - overrides from dependencies are not applied.

So the error here is maybe not fine-grained enough? The overridden package is within the range allowed by the non-dev dependencies, so the tested version is what user would use (but not what web_socket_channel is supposed to work with).

We should perhaps only error if the overridden version is not fulfilling a resolution without dev_dependencies?

@jonasfj WDYT?

**Comment by jonasfj** [comment]
> We should perhaps only error if the overridden version is not fulfilling a resolution without dev_dependencies?

I think this would be nice improvement.

-------------------------

@Daegalus, you are in a corner case.. I imagine you could publish if just remove comment out your dev-dependencies while publishing. There is no need for `dev_dependencies` in packages published to pub.dev -- we dream of running tests for the packages, but we're not there yet, so for now it should be of no consequence that you remove your dev_dependencies while publishing.

Long-term the underlying issue here is likely to be fixed. The problem is that `package:test` was migrated before it's dependencies, this is discouraged, but in this specific case the downsides outweigh the benefits (with dependency cycles you have to break somewhere).

**Comment by jonasfj** [comment]
note. I'm not suggesting you permanently remove you dev_dependencies, or stop testing :rofl:  -- just that right now for the purpose of getting a prerelease published it's a viable option.
