### ISSUE TITLE
Question: Using this project for automated pubspec.lock file updates

### ISSUE THREAD

**Issue by IchordeDionysos** [dart-lang/pub#2947]
I have more of an implementation question, rather than a concrete issue ☺️ 

I am currently, working on bringing Pub support for Dependabot, and for that, I need a way to update the lock file.

What I could do in theory is to write a regex to replace the changed parts (that's what's done for other package managers), but honestly, I try to avoid it as it's less readable.

What I've tried instead was to load the YAML file, manipulate it and write it back.
This does not work for a simple reason as Pub, inserts the "Generated by pub" footer, adding this manually in the dependabot code is even less clean.

--- 

Now to my question:
I've found this project [pubspec_parse](https://github.com/dart-lang/pubspec_parse) for parsing the `pubspec.yaml` file, but this does not support lock files nor serializing the object back to a file.

The only official place where this functionality exists is [here](https://github.com/dart-lang/pub/blob/master/lib/src/lock_file.dart#L314).

What are your thoughts on exposing/extracting this functionality somehow for tools like Dependabot?

See https://github.com/dependabot/dependabot-core/pull/3438 for the Dependabot PR.

**Comment by IchordeDionysos** [comment]
@jonasfj because I saw your comment here: https://github.com/google/dart-neats/issues/102

So for manipulating the `pubspec.yaml` I could use the `yaml_edit` library, right?

This should in theory also work for the lock file right, from my experimentation.
But only if there is special handling for quotation using for example `ScalarStyle.DOUBLE_QUOTED` where appropriate.

**Comment by jonasfj** [comment]
@IchordeDionysos why do you need to manually modify `pubspec.lock`?

We added `dart pub outdated --json` with the idea in-mind that things like dependabot would:
 * Create temporary directory, write `pubspec.yaml` to said directory,
 * Run `dart pub outdated --json`
Then use this output to determine state of outdated dependencies.

We also have `dart pub upgrade` which overwrites `pubspec.lock` (if anything is upgraded).
I imagine, dependabot could (if a `pubspec.lock` exists):
 * write `pubspec.yaml` and `pubspec.lock` to temporary directory,
 * Run `dart pub upgrade`
 * Do a diff between the new and the old `pubspec.lock` to get changes.

Note: some projects don't commit a `pubspec.lock`, this mostly makes sense if you are working on a package that is later published on pub.dev -- because then you always want to test against the latest dependencies. You might even have a CI script that does both:
 *  `dart pub upgrade && dart test` to test the latest dependencies, and,
 *  `dart pub downgrade && dart test` to test the oldest allowed dependencies.

----------------------

There is also `dart pub upgrade --major-versions` which modifies both the `pubspec.yaml` and `pubspec.lock`.
Perhaps you simply want to run `dart pub upgrade --major-versions` and then generate a diff for `pubspec.yaml` and `pubspec.lock`. Probably still using `dart pub outdated --json` to detect and report packages that can't be upgraded.

-----------------

By the way, I'm happy to help, if you want to chat about pub+dependabot feel free to drop me a line, I'm `jonasfj@google.com`  or `jonasfj#4282` on [discord](https://github.com/flutter/flutter/wiki/Chat) -- I try to hangout in `hackers-pub-dev-...` with some success, but if you ping me I might notice.


--------------------

Side note: When running `dart pub` on dependabot it might be nice to set: `CI=true` and [`PUB_ENVIRONMENT=dependabot`](https://github.com/dart-lang/pub/blob/018c965030716038b61188d0c2171797ff16b31c/lib/src/http.dart#L54-L57) or something like that.

**Comment by IchordeDionysos** [comment]
@jonasfj thanks that's helpful already.

Dropped a few comments on Discord with some background info on Dependabot and the reason why I implemented it the way I did.

-- 

And thanks for the hint with the PUB_ENVIRONMENT, implemented it.
Also the API calls will send a proper User-Agent and now also `dependabot` as the environment 👍
