### ISSUE TITLE
Consider parsing example pubspec.yaml files for `false_secrets`

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/pub#3141]
For background see https://github.com/dart-lang/pub/pull/3049#issuecomment-924512215 and https://github.com/flutter/flutter/issues/90477#issuecomment-924336284

Responding to the former:

> we currently don't look at nested pubspecs at all. I'm not sure it makes much sense to do so. After all it's the root package you're publishing, and it's the root package that contains the entirety of the example/ package.

Counter-argument: `example` is a self-contained package, and *all* other configuration related to that package is in pubspec.yaml. Putting its exception information in a *completely different package* just because it happens to be inside it makes much less sense IMO.

> Reading the contents of nested pubspecs seems a bit weird.. and I'm not sure it's wise to start doing a thing like that.
Right now a nested pubspec.yaml is just a data-file that gets published with the package.

Having an `example/` directory is extremely common at least in Flutter packages, so I'm not sure why having pub.dev understand that concept would be weird.

> Could we do something to avoid having these secrets? Or maybe put all of them in a file called false_secrets.dart, so that only one pattern is necessary...

See the second link above; one of our instances of this involves HTML, ObjC, Dart, JSON, and a plist. Consolidating to one file would require a bunch of custom build rules that would be much more annoying than the patterns.

/cc @jonasfj

**Comment by jonasfj** [comment]
> Counter-argument: `example` is a self-contained package, and all other configuration related to that package is in `pubspec.yaml`.

I see some packages with `example/foo/pubspec.yaml` or other things like that. Because they have multiple examples. I also see few dart-lang packages with `example/pubspec.yaml`. Nor is entirely clear from documentation:
https://dart.dev/tools/pub/package-layout#examples

As I recall we updated documentation to better allow for such patterns because Flutter made it so pervasive.

My point being that: deciding that `example/` is a nested standalone example app/package is a new decision. And maybe it's a decision we should just make already :rofl: Then start scoring for it in `pana`, reducing pub points for packages that have multiple examples, etc. because that's not what the convention is. Just saying, such decision have implications :D

--------------

We could ofcourse make the less pretty decision that leak-detection and false-secrets is a heuristic, hence, it's natural that we look for any `pubspec.yaml` that contains `false_secrets` and ignore all of these. Since it's tweaking a heuristic we don't necessarily have to make a decision around `example/` or make that special in any way.

**Comment by stuartmorgan** [comment]
> My point being that: deciding that `example/` is a nested standalone example app/package is a new decision.

It isn't really stand-alone (it generally has a path reference, because otherwise it would be a nightmare to update to match changes in the package), but the fact that it's a nested package isn't a decision, it's an objective fact. That directory *is* a package.

The decision in the context of this issue is: should the secret detection system ignore the reality that nested packages are a thing that exists, or should it understand the reality that they do and improve the ergonomics of the ignore-list by leveraging that?

**Comment by ditman** [comment]
> deciding that `example` is a nested standalone example app/package is a new decision. And maybe it's a decision we should just make already 🤣 Then start scoring for it in `pana`, reducing pub points for packages that have multiple 

I thought this decision had already been made? `pana` deducts 10 points if your package does *not* contain an `example`:

* https://pub.dev/packages/cross_file/score (See the "Provide documentation" section)

IMO multiple `examples` are nice, and should be supported. We could use multiple examples to differentiate between the "example app used to run integration_tests of a package" and didactic examples for users to look at, or to have separate examples to display multiple features of a package (instead of a huge monolithic example attempting to show off everything, like Google Maps has).

**Comment by natebosch** [comment]
`false_secrets` is a concern related to the publishing of a package. `example` is not a published package.

I don't think we should add the complexity of extra searching and parsing for this.
