### ISSUE TITLE
Check that PUB_HOSTED_URL is used by "dart pub publish"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub#3280]
Check that `PUB_HOSTED_URL` is used by `dart pub publish`, when no `publish_to` URL is specified.

**Comment by sigurdm** [comment]
The logic goes 

1. publish to `--server` if that is passed as command-line option
2. otherwise publish to `publish_to` if that is specified in the pubspec
3. otherwise use `cache.sources.hosted.defaultUrl`:
    1. if `PUB_HOSTED_URL` is present in the environment use that
    2. otherwise use `pub.dartlang.org` (the old name for pub.dev, still used by the client).
 
It is encoded here: https://github.com/dart-lang/pub/blob/dcb6abac2d7d43258c03b348be42bf4aab9529b1/lib/src/command/lish.dart#L39

**Comment by jonasfj** [comment]
I think users of private package repositories should always use `publish_to` regradless, that way they reduce the risk they accidentally publish their package to `pub.dev`.

**Comment by sigurdm** [comment]
> I think users of private package repositories should always use publish_to regradless, that way they reduce the risk they accidentally publish their package to pub.dev.

I think that is not always true - there is value in being able to mirror packages from pub.dev unmodified.
