### ISSUE TITLE
dart pub upgrade --major-versions is worse than without the option

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub#3456]
# Environment

- `pub version` or `flutter pub version`:

I don't have a `pub version` command but `dart --version` is `Dart SDK version: 2.17.3 (stable) (Wed Jun 1 11:06:41 2022 +0200) on "linux_x64`.

- OS version: Linux 5.17.6
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

`dart pub upgrade --major-versions` is failing to find solutions that `dart pub upgrade` finds.

```yaml
name: mypkg
version: 0.0.1
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  collection: ^1.15.0-nullsafety.4
  crypto: ^3.0.1
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  markdown: ^4.0.1
  path: ^1.6.2
  protobuf: ^2.0.1
dev_dependencies:
  lints: ^1.0.1
  test: ^1.15.7
```

with with this pubspec.lock: https://gist.github.com/sortie/0e70bee328c285b783af01bdbee9e83c

## Expected behavior

`dart pub upgrade --major-version` just gives me all the good new stuff and finds at least the solutions the ordinary variant can find.

## Actual behavior

Running `dart pub upgrade --major-version` fails to resolve all the available versions:

```
Resolving dependencies... (1.4s)
  _discoveryapis_commons 1.0.2 (1.0.3 available)
  _fe_analyzer_shared 36.0.0 (40.0.0 available)
  analyzer 3.3.1 (4.1.0 available)
  args 2.3.0 (2.3.1 available)
  async 2.8.2 (2.9.0 available)
  collection 1.15.0 (1.16.0 available)
  convert 3.0.1 (3.0.2 available)
  coverage 1.1.0 (1.3.2 available)
  crypto 3.0.1 (3.0.2 available)
  fixnum 1.0.0 (1.0.1 available)
  frontend_server_client 2.1.2 (2.1.3 available)
> googleapis 9.1.0 (was 8.1.0)
  googleapis_auth 1.3.0 (1.3.1 available)
  http_parser 4.0.0 (4.0.1 available)
> lints 2.0.0 (was 1.0.1)
> markdown 5.0.0 (was 4.0.1)
  meta 1.7.0 (1.8.0 available)
  mime 1.0.1 (1.0.2 available)
  path 1.8.1 (1.8.2 available)
  pub_semver 2.1.0 (2.1.1 available)
  shelf 1.2.0 (1.3.0 available)
  source_span 1.8.2 (1.9.0 available)
  string_scanner 1.1.0 (1.1.1 available)
  test 1.20.1 (1.21.1 available)
  test_core 0.4.11 (0.4.13 available)
  typed_data 1.3.0 (1.3.1 available)
  vm_service 8.2.0 (8.3.0 available)
  web_socket_channel 2.1.0 (2.2.0 available)
  webkit_inspection_protocol 1.0.0 (1.1.0 available)
  yaml 3.1.0 (3.1.1 available)
Changed 3 dependencies!

Changed 3 constraints in pubspec.yaml:
  googleapis: ^8.1.0 -> ^9.1.0
  markdown: ^4.0.1 -> ^5.0.0
  lints: ^1.0.1 -> ^2.0.0
```

However, running first without `--major-versions` works:

```
$ dart pub upgrade
Resolving dependencies... (1.5s)
> _discoveryapis_commons 1.0.3 (was 1.0.2)
> _fe_analyzer_shared 40.0.0 (was 36.0.0)
> analyzer 4.1.0 (was 3.3.1)
> args 2.3.1 (was 2.3.0)
> async 2.9.0 (was 2.8.2)
  boolean_selector 2.1.0
  charcode 1.3.1
> collection 1.16.0 (was 1.15.0)
> convert 3.0.2 (was 3.0.1)
> coverage 1.3.2 (was 1.1.0)
> crypto 3.0.2 (was 3.0.1)
  file 6.1.2
> fixnum 1.0.1 (was 1.0.0)
> frontend_server_client 2.1.3 (was 2.1.2)
  glob 2.0.2
  googleapis 8.1.0 (9.1.0 available)
> googleapis_auth 1.3.1 (was 1.3.0)
  http 0.13.4
  http_multi_server 3.2.0
> http_parser 4.0.1 (was 4.0.0)
  io 1.0.3
  js 0.6.4
  lints 1.0.1 (2.0.0 available)
  logging 1.0.2
  markdown 4.0.1 (5.0.0 available)
  matcher 0.12.11
> meta 1.8.0 (was 1.7.0)
> mime 1.0.2 (was 1.0.1)
  node_preamble 2.0.1
  package_config 2.0.2
> path 1.8.2 (was 1.8.1)
  pool 1.5.0
  protobuf 2.0.1
> pub_semver 2.1.1 (was 2.1.0)
> shelf 1.3.0 (was 1.2.0)
  shelf_packages_handler 3.0.0
  shelf_static 1.1.0
  shelf_web_socket 1.0.1
  source_map_stack_trace 2.1.0
  source_maps 0.10.10
> source_span 1.9.0 (was 1.8.2)
  stack_trace 1.10.0
  stream_channel 2.1.0
> string_scanner 1.1.1 (was 1.1.0)
  term_glyph 1.2.0
> test 1.21.1 (was 1.20.1)
  test_api 0.4.9
> test_core 0.4.13 (was 0.4.11)
> typed_data 1.3.1 (was 1.3.0)
> vm_service 8.3.0 (was 8.2.0)
  watcher 1.0.1
> web_socket_channel 2.2.0 (was 2.1.0)
> webkit_inspection_protocol 1.1.0 (was 1.0.0)
> yaml 3.1.1 (was 3.1.0)
Changed 27 dependencies!
3 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
$ dart pub upgrade --major-versions
Resolving dependencies... (1.3s)
> googleapis 9.1.0 (was 8.1.0)
> lints 2.0.0 (was 1.0.1)
> markdown 5.0.0 (was 4.0.1)
Changed 3 dependencies!

Changed 3 constraints in pubspec.yaml:
  googleapis: ^8.1.0 -> ^9.1.0
  markdown: ^4.0.1 -> ^5.0.0
  lints: ^1.0.1 -> ^2.0.0

```

**Comment by sigurdm** [comment]
I would expect the same.

@jonasfj do you have a clue what happens here?

Maybe this is just a fluke caused by the solver choosing a different path though the solve-space. It only promises _a_ solution not 'the best' (for any definition of 'the best'). Still the heuristic should default to trying the newest version first, so this is surprising.

**Comment by jonasfj** [comment]
Maybe we somehow pass in the lockfile when doing `upgrade --major-versions`, but yes, I would expect the same.

**Comment by sigurdm** [comment]
Seems we are using `UpgradeType.get` when `--major-versions`. I think that might be the reason here:

https://github.com/dart-lang/pub/blob/d8f4c549039d0652d0a1f38e2a7292df73d4ff74/lib/src/command/upgrade.dart#L236

Seems like we did that on purpose here: https://github.com/dart-lang/pub/pull/3295, the backing issue doesn't really say why we want this: https://github.com/dart-lang/pub/issues/3257.

I vaguely recall @mit-mit being surprised by everything upgrading at once....

@jonasfj any thoughts?

**Comment by mit-mit** [comment]
Sorry, I don't recall. My recollection was that we wanted `--major-versions` to work similar to removing all the upper constraints in the pubspec.

**Comment by jonasfj** [comment]
Actually, I think I recall some of the logic here.

We wanted `dart pub upgrade foo` and `dart pub upgrade --major-versions foo` to be conservative. So that it is reasonably possible to only upgrade one dependency at the time.

This is actually not a bad idea, but I think I personally would never want to upgrade a little at the time.

The surprising consequences is that:
 * `dart pub upgrade foo` only unlocks `foo` and keeps everything else locked to `pubspec.lock`, which frequently means that a possible upgrade of `foo` is held back, because other dependencies remains locked.
 * Similarly, for `dart pub upgrade --major-versions foo` removes upper-bounds for `foo` (and increases lower-bounds, so as to trigger a forced upgrade), but then does a conservative `dart pub get` resolution; because we want to avoid affecting anything but `foo` if _heuristically_ possible.

I think we should be less conservative :D, but I think the reasoning is that we imagined people would occasionally want to upgrade one thing at the time.

**Comment by sigurdm** [comment]
Ah so we did https://github.com/dart-lang/pub/pull/3295 for the single-dependency case...

We probably should distinguish, and if no arguments are given we should use UpgradeType.upgrade, and otherwise UpgradeType.get...
