### ISSUE TITLE
Inconsistent encoding of hosted-dependency URLs

### ISSUE THREAD

**Issue by pattobrien** [dart-lang/pub#3581]
# Environment

- Dart version (run `dart --version`): 2.17.5 (stable)
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): macos_arm64, MacOS 12.6
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

Cloudsmith is a 3rd party pub SaaS platform, referenced [in the dart documentation](https://dart.dev/tools/pub/custom-package-repositories#dart-package-repositories-as-a-service). When using their service with pub (```hosted``` dependency), the url backslashes are improperly encoded. This causes issues when trying to create any tool that is expecting a properly encoded url, such as when using a package like ```package_config```, which I'm currently utilizing while creating a custom analyzer tool.

As an example, I use the below dependency in my pubspec file.

```yaml
# pubspec file
dependencies:
  sidecar_analyzer_plugin:
    hosted: https://dart.cloudsmith.io/fine-designs/sidecar_analyzer_plugin/
    version: ^0.1.15

```

## Expected behavior

the url: ```dart.cloudsmith.io/fine-designs/fine_file_service/```
should encode to: ```~/.pub-cache/hosted/dart.cloudsmith.io%2Ffine-designs%2Ffine_file_service%2F```
where ```%2F``` is the **hex-based** representation of the character ```/```.

## Actual behavior
the url: ```dart.cloudsmith.io/fine-designs/fine_file_service/```
incorrectly encodes to: ```~/.pub-cache/hosted/dart.cloudsmith.io%47fine-designs%47fine_file_service%47```
where ```%47``` is the **decimal-based** representation of the character ```/```.

furthermore, the ```package_config.json``` file contains the dependency with the following "rootUri":

```json
"rootUri": "file:///Users/pattobrien/.pub-cache/hosted/dart.cloudsmith.io%2547fine-designs%2547sidecar_analyzer_plugin%2547/sidecar_analyzer_plugin-0.1.15"
```

this seems to indicate that the ```%47``` character from the pub-cache path is encoded a second time to become ```%2547``` (the url encoded ASCII representation of ```%``` is ```%25```)

## --trace output

n/a

**Comment by sigurdm** [comment]
This is a known bug - see comments in the source-code: https://github.com/dart-lang/pub/blob/8e306f33daa291f8483af53e6da749cc11bacf7e/lib/src/source/hosted.dart#L1059-L1068

Unfortunately it is hard to change without breaking compatibility with old caches.

In most cases you should indeed only look at the .dart_tool/package_config.json file to find the dependencies instead of trying to guess where they are yourself based on the host-name. That is the interface pub interacts with other dart-tools through.

> ... this seems to indicate that the %47 character from the pub-cache path is encoded a second time ...

The package_config.json contains file-urls not file paths, so they indeed are encoded a second time.  

Consider this program:

```dart
import 'dart:io';
main() {
  print(Uri.file('%')); // Making a uri from a file-path causes it to be uri-encoded
  print(File.fromUri(Uri.file('%')).path); // making a File from a Uri will uri-decode it.
}
```

It prints
```
%25
%
```


Hope that helps. I'll close the issue, but feel free to reopen if something is unclear.
