### ISSUE TITLE
2.12 back compat in 3.0 doesn't work correctly in dev SDKs

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#3600]
In https://github.com/dart-lang/pub/pull/3572 we added support for 2.12 and later SDKs in a 3.0 SDK.  Everything works great with a stable sdk version.

With a dev sdk version: a) 2.9 packages are allowed to resolve, b) there is some confusing output.

Patch to change the version:
https://gist.github.com/mit-mit/87eb75e7195b19c427ecd6232bae8cb8

**Comment by mit-mit** [comment]
cc @sigurdm

**Comment by sigurdm** [comment]
> With a dev sdk version: a) 2.9 packages are allowed to resolve, b) there is some confusing output.

This is due to the logic introduced when introducing dart 2. It makes a dev-release compatible with pre-major-increment packages (added [here](https://github.com/dart-lang/pub/commit/aad65fe5bad7e8b7a6192835eb59b682cb15ecab)).

@jonasfj what do you think, should we just rip this out,and rely only on the new logic, or should we change the order we do the checks, so the warning only comes up for packages that are pre-2.12 eg. 2.9.

**Comment by sigurdm** [comment]
We have removed the entire logic for allowing prereleases being used with legacy packages. They would anyway not be compatible as they won't be null-safe.

Probably we will have to introduce a new hack for 4.0.0. ...
