### ISSUE TITLE
Dev branch: Unexpected modifications of pubspec.lock

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#3687]
# Environment

- Dart version (run `dart --version`): 2.19.0-440.0.dev
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): ubuntu-22.04
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

The latest Dart dev version seems to be modifying `pubspec.lock` unexpectedly at some point between beginning a `dart run` execution and executing a test. This breaks our tests, which check the time a required file was generated against `pubspec.lock` to ensure that the file is up-to-date. Is it possible that this is related to https://github.com/dart-lang/sdk/issues/50422?

An example failing GitHub action: https://github.com/sass/dart-sass/actions/runs/3589202911/jobs/6041396294

## Expected behavior

I would expect `pubspec.lock` not to be modified unless I actually run `pub get` and it changes the file.

## Actual behavior

`pubspec.lock` is modified

**Comment by sigurdm** [comment]
I think this has the same root-cause as https://github.com/dart-lang/sdk/issues/50617 (we redo the resolution unnecessarily in dart run). 
It should be fixed by: https://github.com/dart-lang/pub/pull/3678  that is rolled into https://github.com/dart-lang/sdk/commit/258598eeb6612df137f6ae445e5a2d8af418da54 [2.19.0-454.0.dev](https://github.com/dart-lang/sdk/releases/tag/2.19.0-454.0.dev) and onwards, and a cherry-pick for the beta-series is here: https://github.com/dart-lang/sdk/issues/50625.

Please reopen if I'm mistaken and/or the upcoming dev-releases still show this issue.

**Comment by nex3** [comment]
Yep, looks like our builds are green again :+1:. Thanks for the quick fix!
