### ISSUE TITLE
pakage version defrence in pubspec.lock and pubspec.yaml and package_config.json 

### ISSUE THREAD

**Issue by manarbajafar** [dart-lang/pub#3770]
I downloaded the code from flutter_notification_listener package github and it worked well even in the background .. Package version 1.0.7

But when I do the same in my project, it doesn't work in the background
And when I looked for the difference..

I found that in two places in the project another version of the package was written, I did not understand why
And when I change it to 1.0.7 the change is not saved even when i clean and pub get the project

![Screenshot (883)](https://user-images.githubusercontent.com/60103703/216595281-4f713da6-49fe-4a57-9228-dd82d936a579.png)

![Screenshot (884)](https://user-images.githubusercontent.com/60103703/216595303-d5d36b77-9c93-46de-a645-e211a8822e20.png)

![Screenshot (885)](https://user-images.githubusercontent.com/60103703/216595324-c652d33c-2557-47b9-a03e-e600e5d45fb5.png)

**Comment by sigurdm** [comment]
`^1.0.7` means "compatible with 1.0.7" so that includes the version 1.3.2.
If there is no existing pubspec.lock, pub will attempt to use the newest version that fits the constraint.

If you want to use v. 1.0.7 specifically try to update the pubspec.yaml file to say:

```yaml
dependencies:
  [...]
  flutter_notification_listener: 1.0.7
  [...]
```

And run `flutter pub get` again.

For more details try reading: https://dart.dev/tools/pub/dependencies

**Comment by manarbajafar** [comment]
> dependencies:
>   [...]
>   flutter_notification_listener: 1.0.7
>   [...]


it is works
Thank you very much and for your quick response
