### ISSUE TITLE
Test secrets in compiled artifacts

### ISSUE THREAD

**Issue by dnys1** [dart-lang/pub#3853]
As part of the leak detection mechanism, several defunct AWS+Google secrets are inlined in the source code currently, e.g. https://github.com/dart-lang/pub/blob/8434b40d6a21dece68c4880e59dbdedfbd6bd7e5/lib/src/validator/leak_detection.dart#L329

While these secrets inherently pose no security risk, they do appear in the compiled `pub` executable and any tool which embeds it. I work on one such tool which uses the embeddable [`pubCommand`](https://github.com/dart-lang/pub/blob/8434b40d6a21dece68c4880e59dbdedfbd6bd7e5/lib/pub.dart#L25) entrypoint, and after trying to commit a pre-compiled version of our tool to GitHub I was flagged with 50+ secret exposure warnings due to their automated [secret scanning](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning) program.

If it's not too much trouble, I may suggest moving these secrets to `test/` so that they are not included in any artifact which embeds the `pub` tooling.

**Comment by sigurdm** [comment]
Hi @dnys1 

Not sure we can move them to `test/` as they are part of the production code (they have to, otherwise they cannot validate that we are not publishing secrets). Perhaps you can exclude the binary from secret scanning: https://docs.github.com/en/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories#excluding-directories-from-secret-scanning-alerts-for-users

Could you tell us more about how you are using the `pubCommand`? Pub is not intended for used as a library outside the dart sdk, and we might easily break you in the future.

**Comment by jonasfj** [comment]
> I work on one such tool which uses the embeddable [pubCommand](https://github.com/dart-lang/pub/blob/8434b40d6a21dece68c4880e59dbdedfbd6bd7e5/lib/pub.dart#L25) entrypoint

Embedding `pub` is not supported.

`pub` is not published as a package. This is intentional. The only public interface for `pub` is the CLI interface in the `dart pub` and `flutter pub`.

I would strongly advise that you call `dart pub` as a subprocess instead of using the `pub` repository as a dependency. 

--------------------------

On topic: I don't think we should take any steps that aims to make it easier to embed `pub`. As this would send the wrong message.

If by putting things in `lib/` we've made it less clear that this use case is unsupported, then perhaps we should move everything into `lib/src/`.


----------------

If you have an important use-case where embedding pub makes sense, please let us know. Designing an embeddable API for pub that would be publish is not something that's easily done -- but if there are good use-cases for this we're certainly interested to learn more about them.

**Comment by dnys1** [comment]
Thank you for the reply. The tool I work on is very similar to melos, the popular repo management tool. We can move to using pub as a process 👍
