### ISSUE TITLE
dart pub get - in all sub folders?

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/pub#3855]
Should we consider letting `dart pub get` do a `dart pub get` in all folders that contain a `pubspec.yaml`?

For example, when one has a package with an `example/` folder that contains a full package.
Or when opening a mono-repo with `pkgs/`.

I often find myself manually going to folders to do `pub get`.

Flutter already does this by default.
And so does Dart-Code the VSCode plugin.

(I believe this was discussed before, but I can't find a tracking bug.)

**Comment by sigurdm** [comment]
Good question

We have `--example` that also runs `pub get` in the example folder. I think we wanted to make that default at some point (to align with `flutter pub get`). @jonasfj should we try to land that change today that it would get into 3.0?

I think one might have `pubspec.yaml` files in subfolders for a number of reasons, so just blindly going through them all seems risky to me.

We have `--directory`/`-C` that can save you from going into the subfolder. Maybe we should make that a multi-value option, in that way one could do a single invocation for all the subfolders (but you would still have to list them explicitly somehow). That would save time, because we only would request version-listings once for shared dependencies.

Side-note: I believe mono-repo supports a command like `monorepo pub get` that runs `pub get` in all repo-folders.

**Comment by dcharkes** [comment]
@DanTup What is the logic in DartCode?

**Comment by sigurdm** [comment]
@dcharkes Does making `--example` be default fix this issue?

I think pub going through all subfolders for `pubspec.yaml`s  is a bit much... should probably be handled by a wrapping script (such as mono-repo) if you have a lot of related packages to update...

**Comment by dcharkes** [comment]
I have lost context of what workflow I had when I was filing this issue. (And I'm mostly work from VS Code with Dart Code where I can rely on it's behavior, so it must have been a workflow where I was not in VS Code.)

Maybe we should not optimize for my specific workflow in a specific point in time. So far my issue only has one upvote, so maybe not many people are running into this.

**Comment by sigurdm** [comment]
Ok, will close as no-action for now. Please reopen/open a new issue if we should consider doing more.

**Comment by dcharkes** [comment]
`dart pub publish --dry-run` implicitly runs a `dart pub get` in the main folder, and subsequently ignores `analysis_options.yaml` `exclude`s, causing https://github.com/dart-lang/ecosystem/issues/150.

`dart pub publish --dry-run` listening to `analysis_options.yaml` would enable me to publish a package version. However, I'd rather not ignore my `test/data/` full Dart projects. Rather, `pub get` should be run in all subfolders with a `pubspec.yaml`.

**Comment by sigurdm** [comment]
> and subsequently ignores analysis_options.yaml excludes.

I'm actually surprised by this. I think we just invoke `dart analyze lib test pubspec.yaml`. I would have guessed that it should pick up excludes...

**Comment by Thelm76** [comment]
I think this issue can be closed with the addition of workspaces #4127
