### ISSUE TITLE
Add a way to tighten the lower bounds in pubspec file.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/pub#3924]
Similar to `dart pub update --null-safety`.

**Comment by ykmnkmi** [comment]
Minor too. From `lints: ^2.0.0` to `lints: ^2.0.1`.

**Comment by sigurdm** [comment]
Ah - makes sense...

@jonasfj WDYT? Should we have `dart pub upgrade --tighten` that excludes everything up to the locked version?

**Comment by jonasfj** [comment]
I don't mind this, we had it in mind when we did `--major-versions`. I think we didn't do it because we couldn't come up with a good name :see_no_evil: 

But if `--tighten` we can do that. We could also do `dart pub upgrade --atleast-locked` or ?


I'm mostly concerned about picking a good name for the feature.
