### ISSUE TITLE
Add a pre-publish check for DevTools extension validation

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/pub#4026]
This is a feature originally requested and discussed here: https://github.com/rrousselGit/provider/pull/832#discussion_r1327918500.

This check would fail on `pub publish --dry-run` if a DevTools extension is expected and none was found.

**Comment by rrousselGit** [comment]
It'd be cool if the check could not only very that the `build` folder exists, but also check that the build output is more recent than the source files.

When thinking about this problem, I realized that gitignored files would still be present on the computer at the publish step. So if publishing locally instead of in a CI, the check could incorrectly pass.

**Comment by sigurdm** [comment]
> When thinking about this problem, I realized that gitignored files would still be present on the computer at the publish step. So if publishing locally instead of in a CI, the check could incorrectly pass.

I think we can get around this problem by only considering files not gitignored.
