### ISSUE TITLE
`dart test` recompiles the test package every time if a package has path dependencies

### ISSUE THREAD

**Issue by DanTup** [dart-lang/pub#4070]
This might not be a bug, but I thought it was worth raising to discuss.

I was trying to run tests using `dart test` sharding to see what the total time difference would be (using more of my CPUs that usually sit idle while I wait for tests 🙂). Using `--concurrency` made no difference (I've not investigated why yet but I thought just testing sharding would be easy). Intermittently, I get failures with errors like this:

```
FAILURES!
Cannot rename file to 'C:\Dev\Google\dart-sdk\sdk\pkg\analysis_server\.dart_tool/pub\bin\test\test.dart-3.3.0-edge.6b5b3cc98a23afb58ffdaebf37941aed257ce885.snapshot', path = 'C:\Dev\Google\dart-sdk\sdk\pkg\analysis_server\.dart_tool/pub\bin\test\tmp5ae60430\test.dart-3.3.0-edge.6b5b3cc98a23afb58ffdaebf37941aed257ce885.snapshot.incremental.temp' (OS Error: Access is denied.
, errno = 5)
PathAccessException: Cannot rename file to 'C:\Dev\Google\dart-sdk\sdk\pkg\analysis_server\.dart_tool/pub\bin\test\test.dart-3.3.0-edge.6b5b3cc98a23afb58ffdaebf37941aed257ce885.snapshot', path = 'C:\Dev\Google\dart-sdk\sdk\pkg\analysis_server\.dart_tool/pub\bin\test\tmp5ae60430\test.dart-3.3.0-edge.6b5b3cc98a23afb58ffdaebf37941aed257ce885.snapshot.incremental.temp' (OS Error: Access is denied.

, errno = 5)
```

It seems like the `test` package might be being recompiled by each shard and because they're running concurrently it causes issues like this. However, I don't see any reason for `test` to be recompiled - nothing has changed - I'm just spawning multiple `dart test` processes with different shard numbers.

Running `dart test --help` I see "Building package executable" every time in the analysis server, but I don't see the same in DDS. Looking through https://github.com/dart-lang/pub/blob/master/lib/src/entrypoint.dart I see some checks for `hasPathDependencies` and noticed that this package (`analysis_server`) does indeed have path dependencies (but DDS does not).

So this leads me to some questions:

- Is it necessary to re-compile if there are path dependencies, even if there are no changes? Could it be detected?
- If I understand correctly, it's compiling `test` here (and not _my_ project, so do path dependencies in my package even matter?)
- If it is necessary (because you can't be certain there aren't changes), could there be some way of overriding this (a flag, an env variable, or something)?
  There are many ways that users can could trigger concurrent `dart test` processes in VS Code in the same project (for example they're running a large number - but not all - tests, and we have to split them up to avoid exceeding the max command line length) so it's possible this issue exists outside of just running shards the way I was trying.

**Comment by sigurdm** [comment]
Hmm, we should only recompile if the path dependency is a dependency of package:test itself.

https://github.com/dart-lang/pub/blob/1779628b386819675130f14326f1e8812901c48f/lib/src/executable.dart#L94
https://github.com/dart-lang/pub/blob/c5c34c3ea7d8d5fee68cf051ca80578b99e6ae14/lib/src/package_graph.dart#L93

But maybe something is broken. Can you make a reproduction?

> Is it necessary to re-compile if there are path dependencies, even if there are no changes? Could it be detected?

We don't really have that logic, but ideally the recompilation should be faster due to incremental compilation using the previous output as input to the compiler.

**Comment by sigurdm** [comment]
Yeah - test depending on analyzer itself means that our package-mutability test is always gonna fail.

But when I tried it, I noticed the first compile took ~10 seconds, the second one took ~1. So the incremental compilation is helping us (by quite a lot) by noticing that nothing has changed.

For the file contention issue I don't really know what we can do. My guess is that it is a windows-only issue, as opened files cannot be overwritten... on mac/linux the snapshot would get overwritten by the last process.

As a specific workaround for working on a dependency of package:test you could manually snapshot the test binary (currently not trivial because you have to manually specify the package test cache-dir) and use that snapshot for subsequent runs.

```
> dart --snapshot=test.snapshot --packages=.dart_tool/package_config.json ~/.pub-cac
he/hosted/pub.dev/test-1.24.9/bin/test.dart
> dart test.snapshot ...
```

 @jonasfj any ideas?

**Comment by DanTup** [comment]
> So the incremental compilation is helping us (by quite a lot) by noticing that nothing has changed.

If it noticed _nothing_ has changed, could it not skip trying to write the file? :)


> For the file contention issue I don't really know what we can do. My guess is that it is a windows-only issue, as opened files cannot be overwritten... on mac/linux the snapshot would get overwritten by the last process.

I don't know how worthwhile it is (probably not if it's just for me, although I do wonder if this general issue could affect anyone running tests in VS Code and just hasn't been raised), but perhaps:

- write the snapshot with a temporary/random name
- move the temporary file over the real name
- if the operation fails, compare whether the files are identical (if not, then throw an exception and fail like we do today, but otherwise just assume it's fine to silently use the locked-but-identical file)

**Comment by sigurdm** [comment]
> If it noticed nothing has changed, could it not skip trying to write the file? :)

It could, but that would require extensive logic checking the age or hash of each file.

Not saying we shouldn't do it but I think it should probably be in the domain of the compiler.

> I don't know how worthwhile it is (probably not if it's just for me, although I do wonder if this general issue could affect anyone running tests in VS Code and just hasn't been raised), but perhaps:

We do use a temporary name for writing the file: https://github.com/dart-lang/pub/blob/be6868ba132c782d9835b1638a634ecb73428579/lib/src/dart.dart#L133

But comparing for bytewise equality with the existing file is not something we do currently - might be worth looking into...

> this general issue could affect anyone running tests in VS Code

I don't think this is specific to VS-code, but any users of `dart run` on windows (dart test is just a thin veil over `dart run test:test`. If the executable is "mutable" in pubs definition we issue a (incremental) compilation for each run, potentially leading to issues on Windows when multiple runs happen in parallel.

For `dart test` specifically, I think the issue is mainly relevant when developing package:test or one of its (many) dependencies.

**Comment by DanTup** [comment]
> I don't think this is specific to VS-code, but any users of `dart run` on windows

Oh yeah, good point.


> For `dart test` specifically, I think the issue is mainly relevant when developing package:test or one of its (many) dependencies.

Yeah, although I think a user could still trigger it fairly easy:

- Run `pub get` to update packages
- Trigger a test run in VS Code that gets split across multiple `dart test` processes (but started at the same time)

That bottom one is unfortunately quite easy to do. If you exclude any tests in the test runner, we can't just run `dart test` and have to name all of the files (minus the excluded one), and in a reasonable size project that often leads to "Command line too long" and so we split across multiple processes to keep each command line short.

A bit off-topic, but if we could write the test arguments to a file and then invoke it with a filename, that would avoid some of that hack, but I'm not sure if it's worthwhile.

**Comment by sigurdm** [comment]
Good point, the issue is also there on first run for "immutable" targets.

**Comment by DanTup** [comment]
sgtm, thanks!
