### ISSUE TITLE
Rename/alias `dependency_overrides` to `override_dependencies`

### ISSUE THREAD

**Issue by ditman** [dart-lang/pub#4246]
This is a very minor annoyance, but I find the `dependency_overrides` attribute name in `pubspec.yaml` a little bit jarring, and well, kind of hard to remember.

The problem I have is that it doesn't align well with the other attributes that it's supposed to modify; so I never guess the correct name at first.

The other related parameters are:

* `dependencies`
* `dev_dependencies`

However to "override dependencies", I need to use `dependency_overrides` (which is "reversed" compared to `dev_dependencies` and doesn't use the `dependencies` word).

Could we accept `override_dependencies` in the pubspec?

(Also, while we're at it, maybe do `development_dependencies` to _AVOID abbreviations and acronyms unless they are obvious_? ;P)

**Comment by sigurdm** [comment]
I tend to agree that these are hard to remember, and I also dislike the unneeded abbreviations. (Also they should probably be [camelCase](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format))

I am however very hesitant to add alternatives here, since we don't control everyone parsing pubspec.yaml, it would break them, and add added complexity (what if both alternatives are present?).

Also I'm not sure these are really "override dependencies".

The way I think of it, the `dependency_overrides` are not  dependencies of the referring package. They are overrides of dependencies **somewhere** in the dependency graph.

I think the best path forward at this is to improve tab-completion/suggestions in the editor, making these easier to type.

**Comment by sigurdm** [comment]
Issue for completion in pubspec.yaml: https://github.com/dart-lang/sdk/issues/54264

**Comment by ditman** [comment]
Agreed! Auto-completion / linting / inline hints / anything would help, really :)

**Comment by sigurdm** [comment]
I'll close this issue for now. Hoping we'll get time to look into tab-completion for pubspec.yaml at some point
